[package]
authors = ["Nikita (rizz) <nj18@nyu.edu>"]
edition = "2021"
name = "merkle-incentives"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "schema"

[[test]]
name = "test-tube"
path = "tests/merkle.rs"
required-features = ["test-tube"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []
test-tube = ["osmosis-test-tube"]

[dependencies]
base64 = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std ={ workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde-json-wasm = { workspace = true }
thiserror = { workspace = true }
rs_merkle = { version = "1.4.2", default-features = false }
osmosis-test-tube = { workspace = true, optional = true }
