[package]
authors = ["Nikita (rizz) <nj18@nyu.edu>"]
edition = "2021"
name = "range-middleware"
version = "0.3.1"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "schema"

[features]
backtraces = ["cosmwasm-std/backtraces"]
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 ={ workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
dex-router-osmosis = { workspace = true }
cl-vault = {path = "../cl-vault", features = ["library"]}
osmosis-std = { workspace = true }
