[package]
name = "interface"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw-orch.workspace = true
cl-vault = { path = "../../contracts/cl-vault" }
range-middleware = { path = "../../contracts/range-middleware" }