[package]
name = "quasar-traits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
sw-storage-plus = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
cw20 = { workspace = true }
