version: "3.9"
services:

  quasar:
    build:
      context: .
      target: dev
    image: quasar:dev
    ports:
      - "1317:1317"
      - "26657:26657"
      - "9090:9090"
    command: "quasarnoded start"

  osmosis:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile.quasar-osmosis
    image: osmosis:dev
    ports:
       - "1417:1317"
       - "26757:26657"
       - "9190:9090"

    command: "osmosisd start"
  