#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/../.." ; pwd)" # Absolute path to project dir
this_dir="${project_dir}/demos/interchain-accounts"
this_script="${this_dir}/$(basename "${0}")"
run_dir="${this_dir}/run"
reset_run="${RESET:-true}"

fail() {
  echo "$*"
  false
}

cmd_exists() {
  type "$1" >/dev/null 2>&1 || fail "command '${1}' not available"
}

env_subst() {
  python -c '
import os, sys
data = sys.stdin.read(65536)
for v in os.environ:
  data = data.replace("$%s" % v, os.environ[v])
  data = data.replace("${%s}" % v, os.environ[v])
sys.stdout.write(data) ; sys.stdout.flush()
'
}

# TODO make macos / darwin version of this
run_in_terminal() {
  gnome-terminal -- "$@"
}

run_chain() {
  (
    local name="$1" ; shift
    local dir="$1"  ; shift

    echo "running ${name} chain"

    cd "$dir"

    local chain_dir="${run_dir}/${name}"

    if [ "$reset_run" == true ] ; then
      rm -rf "$chain_dir"
    fi

    export home_dir="${chain_dir}/home"
    mkdir -p "$home_dir"

    cat "${this_dir}/${name}.yml" | env_subst >| "${chain_dir}/config.yml"

    ignite chain serve --config "${chain_dir}/config.yml" --reset-once -v
  )
}

start_intertx_1() { run_chain "intertx-1"  "${project_dir}/../contrib/interchain-accounts-demo" ; }
start_intertx_2() { run_chain "intertx-2"  "${project_dir}/../contrib/interchain-accounts-demo" ; }

start_all() {
  if [ "$reset_run" == true ] ; then
    rm -rf ~/.ignite/
  fi

  run_in_terminal "$this_script" start_intertx_1
  sleep 1
  run_in_terminal "$this_script" start_intertx_2
  sleep 1
}

init_relayer() {
  (
    cd "$this_dir"

    # Alice on 1
    hermes -c hermes.toml keys restore "intertx-1"  --name "testkey1" --mnemonic "jungle law popular reunion festival horn divorce quarter image gather october weird slide trend resource render abuse food tomorrow multiply price fun ask quarter"
    # Alice on 2
    hermes -c hermes.toml keys restore "intertx-2" --name "testkey2" --mnemonic "act scale exhibit enough swamp vivid bleak eagle giggle brass desert debris network scrub hazard fame salon normal over between inform advance sick dinner"

    hermes -c hermes.toml create connection "intertx-1" "intertx-2"
    hermes -c hermes.toml create channel    "intertx-1" "connection-0" --port-a "transfer" --port-b "transfer"

    hermes -c hermes.toml start
  )
}

intertx_1() {
  local home_dir="${run_dir}/intertx-1/home"

  icad \
    --home "$home_dir" \
    --node=http://localhost:26659 \
    --chain-id "intertx-1" \
    "$@"
}

intertx_1_q() {
  intertx_1 query "$@"
}

intertx_1_tx() {
  intertx_1 tx --from alice "$@"
}

intertx_2() {
  local home_dir="${run_dir}/intertx-2/home"

  icad \
    --home "$home_dir" \
    --node=http://localhost:26559 \
    --chain-id "intertx-2" \
    "$@"
}

intertx_2_q() {
  intertx_2 query "$@"
}

intertx_2_tx() {
  intertx_2 tx --from alice "$@"
}

test -d "${project_dir}/../contrib/interchain-accounts-demo" || fail "intertx dir not found"

cmd_exists "icad"
cmd_exists "hermes"

"$@"
