#!/bin/bash

set -e

REPO_ROOT=$(git rev-parse --show-toplevel)

CHANGES=$(git diff --name-only origin/main)


if [ -z "$CHANGES" ]
then
  echo "No changes"
  exit 1
fi

update_schemas_and_formatting() {
  local workspace=$1
  local contract=$2
  if [[ $CHANGES == *${workspace}/contracts/${contract}* ]]
  then
    echo "Changes in ${contract} contract"
    cd ${REPO_ROOT}/smart-contracts/${workspace}/contracts/${contract}

    # generate schemas
    cargo schema
    NEW_CHANGES=$(git diff --name-only origin/main..HEAD)
    if [[ $NEW_CHANGES == *schema/* ]]
    then
      git add schema
    else
      echo "No schema changes for ${contract}."
    fi

    # fix formatting
    cargo fmt --all
    cd ${REPO_ROOT}
    NEW_CHANGES=$(git diff --name-only origin/main..HEAD --diff-filter=AMR)
    git add $NEW_CHANGES
  fi
}

update_schemas_and_formatting osmosis lst-dex-adapter-osmosis
update_schemas_and_formatting osmosis dex-router-osmosis
update_schemas_and_formatting osmosis token-burner
update_schemas_and_formatting osmosis cl-vault
update_schemas_and_formatting osmosis merkle-incentives
update_schemas_and_formatting osmosis range-middleware
update_schemas_and_formatting quasar babylon-vault
