// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbank/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WhiteListedDenomInOrion struct {
	OriginName   string `protobuf:"bytes,1,opt,name=originName,proto3" json:"originName,omitempty" yaml:"origin_name"`
	OnehopQuasar string `protobuf:"bytes,2,opt,name=onehopQuasar,proto3" json:"onehopQuasar,omitempty" yaml:"onehop_quasar"`
	OnehopOsmo   string `protobuf:"bytes,3,opt,name=onehopOsmo,proto3" json:"onehopOsmo,omitempty" yaml:"onehop_osmo"`
}

func (m *WhiteListedDenomInOrion) Reset()         { *m = WhiteListedDenomInOrion{} }
func (m *WhiteListedDenomInOrion) String() string { return proto.CompactTextString(m) }
func (*WhiteListedDenomInOrion) ProtoMessage()    {}
func (*WhiteListedDenomInOrion) Descriptor() ([]byte, []int) {
	return fileDescriptor_e82e1979e19996b6, []int{0}
}
func (m *WhiteListedDenomInOrion) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WhiteListedDenomInOrion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WhiteListedDenomInOrion.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WhiteListedDenomInOrion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WhiteListedDenomInOrion.Merge(m, src)
}
func (m *WhiteListedDenomInOrion) XXX_Size() int {
	return m.Size()
}
func (m *WhiteListedDenomInOrion) XXX_DiscardUnknown() {
	xxx_messageInfo_WhiteListedDenomInOrion.DiscardUnknown(m)
}

var xxx_messageInfo_WhiteListedDenomInOrion proto.InternalMessageInfo

func (m *WhiteListedDenomInOrion) GetOriginName() string {
	if m != nil {
		return m.OriginName
	}
	return ""
}

func (m *WhiteListedDenomInOrion) GetOnehopQuasar() string {
	if m != nil {
		return m.OnehopQuasar
	}
	return ""
}

func (m *WhiteListedDenomInOrion) GetOnehopOsmo() string {
	if m != nil {
		return m.OnehopOsmo
	}
	return ""
}

// Params defines the parameters for the module.
type Params struct {
	MinOrionEpochDenomDollarDeposit github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=minOrionEpochDenomDollarDeposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"minOrionEpochDenomDollarDeposit" yaml:"min_orion_epoch_dollar_deposit"`
	WhiteListedDenomsInOrion        []WhiteListedDenomInOrion              `protobuf:"bytes,2,rep,name=whiteListedDenomsInOrion,proto3" json:"whiteListedDenomsInOrion" yaml:"whitelisted_denoms_in_orion"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_e82e1979e19996b6, []int{1}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetWhiteListedDenomsInOrion() []WhiteListedDenomInOrion {
	if m != nil {
		return m.WhiteListedDenomsInOrion
	}
	return nil
}

func init() {
	proto.RegisterType((*WhiteListedDenomInOrion)(nil), "abag.quasarnode.qbank.WhiteListedDenomInOrion")
	proto.RegisterType((*Params)(nil), "abag.quasarnode.qbank.Params")
}

func init() { proto.RegisterFile("qbank/params.proto", fileDescriptor_e82e1979e19996b6) }

var fileDescriptor_e82e1979e19996b6 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x8a, 0xd5, 0x30,
	0x14, 0x6e, 0xee, 0xc8, 0x80, 0xd1, 0x55, 0x19, 0xb5, 0xb8, 0x68, 0x86, 0x80, 0x72, 0x11, 0x4c,
	0x41, 0xc1, 0xc5, 0xe0, 0xea, 0x52, 0x17, 0x82, 0x38, 0xda, 0xcd, 0x80, 0x9b, 0x90, 0xb6, 0xa1,
	0x0d, 0xd3, 0xe4, 0x74, 0x9a, 0x0e, 0x3a, 0x6f, 0xe1, 0x4a, 0x5c, 0xea, 0xd3, 0x38, 0xe0, 0x66,
	0x96, 0xe2, 0xa2, 0xc8, 0xbd, 0x6f, 0xd0, 0x27, 0x90, 0x26, 0x55, 0xc7, 0x9f, 0x8b, 0xab, 0x36,
	0xe4, 0x3b, 0xdf, 0x5f, 0x0e, 0x0e, 0x4f, 0x72, 0x61, 0x8e, 0x93, 0x56, 0x74, 0x42, 0x5b, 0xd6,
	0x76, 0xd0, 0x43, 0x78, 0x43, 0xe4, 0xa2, 0x62, 0x27, 0xa7, 0xc2, 0x8a, 0xce, 0x40, 0x29, 0x99,
	0xc3, 0xdc, 0xde, 0xab, 0xa0, 0x02, 0x87, 0x48, 0xa6, 0x3f, 0x0f, 0xa6, 0x9f, 0x10, 0xbe, 0x75,
	0x54, 0xab, 0x5e, 0x3e, 0x53, 0xb6, 0x97, 0x65, 0x2a, 0x0d, 0xe8, 0xa7, 0xe6, 0xb0, 0x53, 0x60,
	0xc2, 0x47, 0x18, 0x43, 0xa7, 0x2a, 0x65, 0x9e, 0x0b, 0x2d, 0x23, 0xb4, 0x8f, 0x96, 0x57, 0x57,
	0x37, 0xc7, 0x81, 0x84, 0x67, 0x42, 0x37, 0x07, 0xd4, 0xdf, 0x71, 0x23, 0xb4, 0xa4, 0xd9, 0x25,
	0x64, 0xf8, 0x18, 0x5f, 0x07, 0x23, 0x6b, 0x68, 0x5f, 0x3a, 0x0f, 0xd1, 0xc2, 0x4d, 0x46, 0xe3,
	0x40, 0xf6, 0xe6, 0x49, 0x77, 0xcb, 0xbd, 0x45, 0x9a, 0xfd, 0x86, 0x76, 0xaa, 0xee, 0x7c, 0x68,
	0x35, 0x44, 0x3b, 0x7f, 0xa9, 0xfa, 0x59, 0xb0, 0x1a, 0x26, 0xd5, 0x9f, 0x48, 0xfa, 0x79, 0x81,
	0x77, 0x5f, 0xb8, 0x1e, 0xc2, 0x8f, 0x08, 0x13, 0xad, 0x7c, 0x8a, 0x27, 0x2d, 0x14, 0xb5, 0x8b,
	0x95, 0x42, 0xd3, 0x88, 0x2e, 0x95, 0x2d, 0x58, 0xd5, 0xcf, 0x71, 0x8e, 0xce, 0x07, 0x12, 0x7c,
	0x1d, 0xc8, 0xdd, 0x4a, 0xf5, 0xf5, 0x69, 0xce, 0x0a, 0xd0, 0x49, 0x31, 0x71, 0xdb, 0xf9, 0x73,
	0xdf, 0x96, 0xc7, 0x49, 0x7f, 0xd6, 0x4a, 0xcb, 0x52, 0x59, 0x8c, 0x03, 0xb9, 0xe3, 0x6d, 0x68,
	0x65, 0x38, 0x4c, 0xfc, 0x5c, 0x4e, 0x02, 0xbc, 0x74, 0xe4, 0xbc, 0xf4, 0xec, 0x34, 0xfb, 0x9f,
	0x7e, 0xf8, 0x0e, 0xe1, 0xe8, 0xf5, 0x1f, 0xc5, 0xdb, 0xb9, 0xf9, 0x68, 0xb1, 0xbf, 0xb3, 0xbc,
	0xf6, 0x80, 0xb1, 0x7f, 0xbe, 0x24, 0xdb, 0xf2, 0x5e, 0xab, 0x7b, 0x53, 0x98, 0x71, 0x20, 0xd4,
	0x5b, 0x74, 0xec, 0x8d, 0x83, 0xf1, 0xd2, 0xd1, 0xf3, 0x1f, 0xa6, 0x69, 0xb6, 0x55, 0xfb, 0xe0,
	0xca, 0xfb, 0x0f, 0x24, 0x58, 0xad, 0xce, 0xd7, 0x31, 0xba, 0x58, 0xc7, 0xe8, 0xdb, 0x3a, 0x46,
	0x6f, 0x37, 0x71, 0x70, 0xb1, 0x89, 0x83, 0x2f, 0x9b, 0x38, 0x78, 0xb5, 0xbc, 0x54, 0xd5, 0xe4,
	0x2f, 0xf9, 0xe5, 0x2f, 0x79, 0x93, 0xf8, 0x7d, 0x74, 0x85, 0xe5, 0xbb, 0x6e, 0xc5, 0x1e, 0x7e,
	0x0f, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x20, 0xc7, 0x3c, 0xa5, 0x02, 0x00, 0x00,
}

func (m *WhiteListedDenomInOrion) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WhiteListedDenomInOrion) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WhiteListedDenomInOrion) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OnehopOsmo) > 0 {
		i -= len(m.OnehopOsmo)
		copy(dAtA[i:], m.OnehopOsmo)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OnehopOsmo)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OnehopQuasar) > 0 {
		i -= len(m.OnehopQuasar)
		copy(dAtA[i:], m.OnehopQuasar)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OnehopQuasar)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OriginName) > 0 {
		i -= len(m.OriginName)
		copy(dAtA[i:], m.OriginName)
		i = encodeVarintParams(dAtA, i, uint64(len(m.OriginName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhiteListedDenomsInOrion) > 0 {
		for iNdEx := len(m.WhiteListedDenomsInOrion) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.WhiteListedDenomsInOrion[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size := m.MinOrionEpochDenomDollarDeposit.Size()
		i -= size
		if _, err := m.MinOrionEpochDenomDollarDeposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WhiteListedDenomInOrion) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OriginName)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OnehopQuasar)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.OnehopOsmo)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinOrionEpochDenomDollarDeposit.Size()
	n += 1 + l + sovParams(uint64(l))
	if len(m.WhiteListedDenomsInOrion) > 0 {
		for _, e := range m.WhiteListedDenomsInOrion {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WhiteListedDenomInOrion) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WhiteListedDenomInOrion: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WhiteListedDenomInOrion: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OriginName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OriginName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnehopQuasar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OnehopQuasar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OnehopOsmo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OnehopOsmo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinOrionEpochDenomDollarDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinOrionEpochDenomDollarDeposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhiteListedDenomsInOrion", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhiteListedDenomsInOrion = append(m.WhiteListedDenomsInOrion, WhiteListedDenomInOrion{})
			if err := m.WhiteListedDenomsInOrion[len(m.WhiteListedDenomsInOrion)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
