// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qbank/query.proto

package types

import (
	context "context"
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryUserDenomDepositRequest struct {
	UserAcc string `protobuf:"bytes,1,opt,name=userAcc,proto3" json:"userAcc,omitempty"`
	Denom   string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryUserDenomDepositRequest) Reset()         { *m = QueryUserDenomDepositRequest{} }
func (m *QueryUserDenomDepositRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserDenomDepositRequest) ProtoMessage()    {}
func (*QueryUserDenomDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{2}
}
func (m *QueryUserDenomDepositRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserDenomDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserDenomDepositRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserDenomDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserDenomDepositRequest.Merge(m, src)
}
func (m *QueryUserDenomDepositRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserDenomDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserDenomDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserDenomDepositRequest proto.InternalMessageInfo

func (m *QueryUserDenomDepositRequest) GetUserAcc() string {
	if m != nil {
		return m.UserAcc
	}
	return ""
}

func (m *QueryUserDenomDepositRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryUserDenomDepositResponse struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryUserDenomDepositResponse) Reset()         { *m = QueryUserDenomDepositResponse{} }
func (m *QueryUserDenomDepositResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserDenomDepositResponse) ProtoMessage()    {}
func (*QueryUserDenomDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{3}
}
func (m *QueryUserDenomDepositResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserDenomDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserDenomDepositResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserDenomDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserDenomDepositResponse.Merge(m, src)
}
func (m *QueryUserDenomDepositResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserDenomDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserDenomDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserDenomDepositResponse proto.InternalMessageInfo

func (m *QueryUserDenomDepositResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type QueryUserDepositRequest struct {
	UserAcc string `protobuf:"bytes,1,opt,name=userAcc,proto3" json:"userAcc,omitempty"`
}

func (m *QueryUserDepositRequest) Reset()         { *m = QueryUserDepositRequest{} }
func (m *QueryUserDepositRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserDepositRequest) ProtoMessage()    {}
func (*QueryUserDepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{4}
}
func (m *QueryUserDepositRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserDepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserDepositRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserDepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserDepositRequest.Merge(m, src)
}
func (m *QueryUserDepositRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserDepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserDepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserDepositRequest proto.InternalMessageInfo

func (m *QueryUserDepositRequest) GetUserAcc() string {
	if m != nil {
		return m.UserAcc
	}
	return ""
}

type QueryUserDepositResponse struct {
	Coins QCoins `protobuf:"bytes,1,opt,name=coins,proto3,castrepeated=github.com/abag/quasarnode/x/qbank/types.QCoins" json:"coins"`
}

func (m *QueryUserDepositResponse) Reset()         { *m = QueryUserDepositResponse{} }
func (m *QueryUserDepositResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserDepositResponse) ProtoMessage()    {}
func (*QueryUserDepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{5}
}
func (m *QueryUserDepositResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserDepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserDepositResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserDepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserDepositResponse.Merge(m, src)
}
func (m *QueryUserDepositResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserDepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserDepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserDepositResponse proto.InternalMessageInfo

func (m *QueryUserDepositResponse) GetCoins() QCoins {
	if m != nil {
		return m.Coins
	}
	return QCoins{}
}

type QueryUserClaimRewardsRequest struct {
	UserAcc string `protobuf:"bytes,1,opt,name=userAcc,proto3" json:"userAcc,omitempty"`
}

func (m *QueryUserClaimRewardsRequest) Reset()         { *m = QueryUserClaimRewardsRequest{} }
func (m *QueryUserClaimRewardsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUserClaimRewardsRequest) ProtoMessage()    {}
func (*QueryUserClaimRewardsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{6}
}
func (m *QueryUserClaimRewardsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserClaimRewardsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserClaimRewardsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserClaimRewardsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserClaimRewardsRequest.Merge(m, src)
}
func (m *QueryUserClaimRewardsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserClaimRewardsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserClaimRewardsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserClaimRewardsRequest proto.InternalMessageInfo

func (m *QueryUserClaimRewardsRequest) GetUserAcc() string {
	if m != nil {
		return m.UserAcc
	}
	return ""
}

type QueryUserClaimRewardsResponse struct {
	Coins QCoins `protobuf:"bytes,1,opt,name=coins,proto3,castrepeated=github.com/abag/quasarnode/x/qbank/types.QCoins" json:"coins"`
}

func (m *QueryUserClaimRewardsResponse) Reset()         { *m = QueryUserClaimRewardsResponse{} }
func (m *QueryUserClaimRewardsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUserClaimRewardsResponse) ProtoMessage()    {}
func (*QueryUserClaimRewardsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{7}
}
func (m *QueryUserClaimRewardsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUserClaimRewardsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUserClaimRewardsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUserClaimRewardsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUserClaimRewardsResponse.Merge(m, src)
}
func (m *QueryUserClaimRewardsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUserClaimRewardsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUserClaimRewardsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUserClaimRewardsResponse proto.InternalMessageInfo

func (m *QueryUserClaimRewardsResponse) GetCoins() QCoins {
	if m != nil {
		return m.Coins
	}
	return QCoins{}
}

type QueryWithdrawableRequest struct {
	UserAccount string `protobuf:"bytes,1,opt,name=userAccount,proto3" json:"userAccount,omitempty"`
	Denom       string `protobuf:"bytes,2,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryWithdrawableRequest) Reset()         { *m = QueryWithdrawableRequest{} }
func (m *QueryWithdrawableRequest) String() string { return proto.CompactTextString(m) }
func (*QueryWithdrawableRequest) ProtoMessage()    {}
func (*QueryWithdrawableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{8}
}
func (m *QueryWithdrawableRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWithdrawableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWithdrawableRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWithdrawableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithdrawableRequest.Merge(m, src)
}
func (m *QueryWithdrawableRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryWithdrawableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithdrawableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithdrawableRequest proto.InternalMessageInfo

func (m *QueryWithdrawableRequest) GetUserAccount() string {
	if m != nil {
		return m.UserAccount
	}
	return ""
}

func (m *QueryWithdrawableRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryWithdrawableResponse struct {
	Coin types.Coin `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin"`
}

func (m *QueryWithdrawableResponse) Reset()         { *m = QueryWithdrawableResponse{} }
func (m *QueryWithdrawableResponse) String() string { return proto.CompactTextString(m) }
func (*QueryWithdrawableResponse) ProtoMessage()    {}
func (*QueryWithdrawableResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_99a391b5aa6457bf, []int{9}
}
func (m *QueryWithdrawableResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryWithdrawableResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryWithdrawableResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryWithdrawableResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryWithdrawableResponse.Merge(m, src)
}
func (m *QueryWithdrawableResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryWithdrawableResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryWithdrawableResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryWithdrawableResponse proto.InternalMessageInfo

func (m *QueryWithdrawableResponse) GetCoin() types.Coin {
	if m != nil {
		return m.Coin
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "abag.quasarnode.qbank.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "abag.quasarnode.qbank.QueryParamsResponse")
	proto.RegisterType((*QueryUserDenomDepositRequest)(nil), "abag.quasarnode.qbank.QueryUserDenomDepositRequest")
	proto.RegisterType((*QueryUserDenomDepositResponse)(nil), "abag.quasarnode.qbank.QueryUserDenomDepositResponse")
	proto.RegisterType((*QueryUserDepositRequest)(nil), "abag.quasarnode.qbank.QueryUserDepositRequest")
	proto.RegisterType((*QueryUserDepositResponse)(nil), "abag.quasarnode.qbank.QueryUserDepositResponse")
	proto.RegisterType((*QueryUserClaimRewardsRequest)(nil), "abag.quasarnode.qbank.QueryUserClaimRewardsRequest")
	proto.RegisterType((*QueryUserClaimRewardsResponse)(nil), "abag.quasarnode.qbank.QueryUserClaimRewardsResponse")
	proto.RegisterType((*QueryWithdrawableRequest)(nil), "abag.quasarnode.qbank.QueryWithdrawableRequest")
	proto.RegisterType((*QueryWithdrawableResponse)(nil), "abag.quasarnode.qbank.QueryWithdrawableResponse")
}

func init() { proto.RegisterFile("qbank/query.proto", fileDescriptor_99a391b5aa6457bf) }

var fileDescriptor_99a391b5aa6457bf = []byte{
	// 675 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xab, 0x36, 0xa8, 0x57, 0x06, 0xb8, 0x06, 0x48, 0xa3, 0xd6, 0xad, 0x2c, 0x21, 0x95,
	0x4a, 0xf8, 0x68, 0x43, 0x55, 0x50, 0xa7, 0xa6, 0x9d, 0x51, 0x6b, 0x09, 0x21, 0xb1, 0x44, 0x67,
	0xe7, 0xe4, 0x5a, 0xc4, 0x3e, 0xc7, 0x67, 0x13, 0xaa, 0x2a, 0x0b, 0x03, 0x62, 0x41, 0x42, 0xe2,
	0x6f, 0x60, 0x61, 0x66, 0xe2, 0x2f, 0xe8, 0x58, 0x89, 0x85, 0x09, 0x50, 0xc2, 0xc2, 0x7f, 0x81,
	0xee, 0x87, 0x83, 0xd3, 0xc4, 0x89, 0x99, 0xd8, 0x7c, 0x2f, 0xef, 0x7b, 0xef, 0x7b, 0xdf, 0xbd,
	0xef, 0x02, 0x6e, 0x76, 0x6c, 0x1c, 0xbc, 0x40, 0x9d, 0x84, 0x44, 0x67, 0x66, 0x18, 0xd1, 0x98,
	0xc2, 0x5b, 0xd8, 0xc6, 0xae, 0xd9, 0x49, 0x30, 0xc3, 0x51, 0x40, 0x5b, 0xc4, 0x14, 0x29, 0xb5,
	0x55, 0x97, 0x52, 0xb7, 0x4d, 0x10, 0x0e, 0x3d, 0x84, 0x83, 0x80, 0xc6, 0x38, 0xf6, 0x68, 0xc0,
	0x24, 0xa8, 0xb6, 0xe5, 0x50, 0xe6, 0x53, 0x86, 0x6c, 0xcc, 0x88, 0xac, 0x86, 0x5e, 0x6e, 0xdb,
	0x24, 0xc6, 0xdb, 0x28, 0xc4, 0xae, 0x17, 0x88, 0x64, 0x95, 0x0b, 0x65, 0xcf, 0x10, 0x47, 0xd8,
	0x4f, 0xf1, 0xcb, 0x32, 0xd6, 0x22, 0x21, 0x65, 0x5e, 0xac, 0x82, 0x15, 0x19, 0xec, 0x7a, 0xf1,
	0x69, 0x2b, 0xc2, 0xdd, 0x51, 0xb8, 0x43, 0x7d, 0x7f, 0x58, 0x52, 0xcf, 0xb6, 0x4f, 0x1b, 0x3b,
	0xd4, 0x4b, 0x7f, 0xaf, 0xb8, 0xd4, 0xa5, 0xe2, 0x13, 0xf1, 0x2f, 0x19, 0x35, 0x2a, 0x00, 0x9e,
	0x70, 0xaa, 0xc7, 0x82, 0x89, 0x45, 0x3a, 0x09, 0x61, 0xb1, 0x61, 0x81, 0xe5, 0x91, 0x28, 0x0b,
	0x69, 0xc0, 0x08, 0xdc, 0x07, 0x65, 0xc9, 0xb8, 0xaa, 0x6d, 0x68, 0x9b, 0x4b, 0x3b, 0x6b, 0xe6,
	0x44, 0x9d, 0x4c, 0x09, 0x6b, 0xcc, 0x5f, 0x7c, 0x5f, 0x2f, 0x59, 0x0a, 0x62, 0x3c, 0x01, 0xab,
	0xa2, 0xe6, 0x53, 0x46, 0xa2, 0x23, 0x12, 0x50, 0xff, 0x48, 0x0e, 0xaa, 0x7a, 0xc2, 0x2a, 0xb8,
	0x96, 0x30, 0x12, 0x1d, 0x38, 0x8e, 0xa8, 0xbe, 0x68, 0xa5, 0x47, 0x58, 0x01, 0x0b, 0x2d, 0x0e,
	0xa8, 0xce, 0x89, 0xb8, 0x3c, 0x18, 0x7b, 0x60, 0x2d, 0xa7, 0x9e, 0x62, 0x7b, 0x1b, 0x94, 0xb1,
	0x4f, 0x93, 0x20, 0x16, 0xf5, 0xe6, 0x2d, 0x75, 0x32, 0xea, 0xe0, 0x4e, 0x06, 0x58, 0x8c, 0x83,
	0xf1, 0x56, 0x03, 0xd5, 0x71, 0x94, 0xea, 0xd4, 0x06, 0x0b, 0x5c, 0xe8, 0x59, 0xb2, 0x9c, 0x1c,
	0xf2, 0xa4, 0xc6, 0x1e, 0x97, 0xe5, 0xd3, 0x8f, 0x75, 0xe4, 0x7a, 0xf1, 0x69, 0x62, 0x9b, 0x0e,
	0xf5, 0x11, 0x07, 0xa0, 0xbf, 0x00, 0xf4, 0x0a, 0xc9, 0x1b, 0x8e, 0xcf, 0x42, 0xc2, 0x14, 0xd0,
	0x92, 0x4d, 0x8c, 0x47, 0x19, 0x21, 0x0f, 0xdb, 0xd8, 0xf3, 0x2d, 0xd2, 0xc5, 0x51, 0x8b, 0xcd,
	0x1e, 0xe2, 0x9d, 0x96, 0xd1, 0x6c, 0x14, 0xfa, 0x5f, 0x26, 0xb1, 0x94, 0xa6, 0xcf, 0xd4, 0x76,
	0x63, 0xbb, 0x4d, 0xd2, 0x29, 0x36, 0xc0, 0x92, 0xa2, 0x3d, 0xbc, 0xc2, 0x45, 0x2b, 0x1b, 0xca,
	0x59, 0x8b, 0x63, 0xb0, 0x32, 0xa1, 0xa6, 0x1a, 0xaf, 0x0e, 0xe6, 0x79, 0x67, 0x35, 0xdd, 0x8a,
	0x29, 0x2d, 0x63, 0x72, 0xcb, 0x98, 0xca, 0x32, 0x26, 0x67, 0xa8, 0x56, 0x57, 0x24, 0xef, 0xfc,
	0x2e, 0x83, 0x05, 0x51, 0x12, 0xbe, 0xd1, 0x40, 0x59, 0xee, 0x36, 0xbc, 0x97, 0xa7, 0xcc, 0x98,
	0x99, 0x6a, 0x5b, 0x45, 0x52, 0x25, 0x41, 0xe3, 0xee, 0xeb, 0xaf, 0xbf, 0x3e, 0xcc, 0xad, 0xc3,
	0xb5, 0x31, 0x1d, 0xb3, 0x0f, 0x06, 0xfc, 0xa2, 0x81, 0x1b, 0x57, 0xf7, 0x1e, 0xd6, 0xa7, 0xf5,
	0xc9, 0x71, 0x5d, 0xed, 0xe1, 0xbf, 0x81, 0x14, 0xcd, 0x7d, 0x41, 0x73, 0x17, 0xd6, 0x73, 0x68,
	0xf2, 0x6b, 0x6a, 0x8a, 0xfb, 0x68, 0xaa, 0xe7, 0x0c, 0x9d, 0xab, 0xab, 0xeb, 0xc1, 0x8f, 0x1a,
	0x58, 0xca, 0xb8, 0x08, 0x9a, 0xb3, 0x29, 0x8c, 0x50, 0x46, 0x85, 0xf3, 0x15, 0xdb, 0x5d, 0xc1,
	0x16, 0xc1, 0xfb, 0xd3, 0xd9, 0x5e, 0xe5, 0x99, 0x8a, 0x9c, 0x35, 0xca, 0x6c, 0x91, 0x27, 0x38,
	0x72, 0xb6, 0xc8, 0x93, 0xbc, 0x58, 0x4c, 0x64, 0x87, 0x23, 0x9b, 0x91, 0x84, 0x66, 0xc8, 0x7f,
	0xd6, 0xc0, 0xf5, 0xac, 0x05, 0xe0, 0x54, 0xd5, 0x26, 0x18, 0xb0, 0xf6, 0xa0, 0x38, 0x40, 0x11,
	0x3e, 0x10, 0x84, 0xf7, 0xe1, 0xe3, 0x1c, 0xc2, 0xdd, 0x0c, 0x68, 0x48, 0x95, 0x5b, 0xb9, 0x87,
	0xce, 0xc5, 0xb2, 0xf4, 0x1a, 0x8d, 0x8b, 0xbe, 0xae, 0x5d, 0xf6, 0x75, 0xed, 0x67, 0x5f, 0xd7,
	0xde, 0x0f, 0xf4, 0xd2, 0xe5, 0x40, 0x2f, 0x7d, 0x1b, 0xe8, 0xa5, 0xe7, 0x9b, 0x45, 0xdf, 0x18,
	0xbb, 0x2c, 0xfe, 0xd9, 0xea, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x13, 0x38, 0xf6, 0xd8,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of UserDenomDeposit items.
	UserDenomDeposit(ctx context.Context, in *QueryUserDenomDepositRequest, opts ...grpc.CallOption) (*QueryUserDenomDepositResponse, error)
	// Queries a list of UserDeposit items.
	UserDeposit(ctx context.Context, in *QueryUserDepositRequest, opts ...grpc.CallOption) (*QueryUserDepositResponse, error)
	// Queries a list of UserClaimRewards items.
	UserClaimRewards(ctx context.Context, in *QueryUserClaimRewardsRequest, opts ...grpc.CallOption) (*QueryUserClaimRewardsResponse, error)
	// Queries a list of Withdrawable items.
	Withdrawable(ctx context.Context, in *QueryWithdrawableRequest, opts ...grpc.CallOption) (*QueryWithdrawableResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.qbank.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserDenomDeposit(ctx context.Context, in *QueryUserDenomDepositRequest, opts ...grpc.CallOption) (*QueryUserDenomDepositResponse, error) {
	out := new(QueryUserDenomDepositResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.qbank.Query/UserDenomDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserDeposit(ctx context.Context, in *QueryUserDepositRequest, opts ...grpc.CallOption) (*QueryUserDepositResponse, error) {
	out := new(QueryUserDepositResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.qbank.Query/UserDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UserClaimRewards(ctx context.Context, in *QueryUserClaimRewardsRequest, opts ...grpc.CallOption) (*QueryUserClaimRewardsResponse, error) {
	out := new(QueryUserClaimRewardsResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.qbank.Query/UserClaimRewards", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Withdrawable(ctx context.Context, in *QueryWithdrawableRequest, opts ...grpc.CallOption) (*QueryWithdrawableResponse, error) {
	out := new(QueryWithdrawableResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.qbank.Query/Withdrawable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of UserDenomDeposit items.
	UserDenomDeposit(context.Context, *QueryUserDenomDepositRequest) (*QueryUserDenomDepositResponse, error)
	// Queries a list of UserDeposit items.
	UserDeposit(context.Context, *QueryUserDepositRequest) (*QueryUserDepositResponse, error)
	// Queries a list of UserClaimRewards items.
	UserClaimRewards(context.Context, *QueryUserClaimRewardsRequest) (*QueryUserClaimRewardsResponse, error)
	// Queries a list of Withdrawable items.
	Withdrawable(context.Context, *QueryWithdrawableRequest) (*QueryWithdrawableResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) UserDenomDeposit(ctx context.Context, req *QueryUserDenomDepositRequest) (*QueryUserDenomDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDenomDeposit not implemented")
}
func (*UnimplementedQueryServer) UserDeposit(ctx context.Context, req *QueryUserDepositRequest) (*QueryUserDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserDeposit not implemented")
}
func (*UnimplementedQueryServer) UserClaimRewards(ctx context.Context, req *QueryUserClaimRewardsRequest) (*QueryUserClaimRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserClaimRewards not implemented")
}
func (*UnimplementedQueryServer) Withdrawable(ctx context.Context, req *QueryWithdrawableRequest) (*QueryWithdrawableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdrawable not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.qbank.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserDenomDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserDenomDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserDenomDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.qbank.Query/UserDenomDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserDenomDeposit(ctx, req.(*QueryUserDenomDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserDepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.qbank.Query/UserDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserDeposit(ctx, req.(*QueryUserDepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UserClaimRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserClaimRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UserClaimRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.qbank.Query/UserClaimRewards",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UserClaimRewards(ctx, req.(*QueryUserClaimRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Withdrawable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryWithdrawableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Withdrawable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.qbank.Query/Withdrawable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Withdrawable(ctx, req.(*QueryWithdrawableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "abag.quasarnode.qbank.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "UserDenomDeposit",
			Handler:    _Query_UserDenomDeposit_Handler,
		},
		{
			MethodName: "UserDeposit",
			Handler:    _Query_UserDeposit_Handler,
		},
		{
			MethodName: "UserClaimRewards",
			Handler:    _Query_UserClaimRewards_Handler,
		},
		{
			MethodName: "Withdrawable",
			Handler:    _Query_Withdrawable_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qbank/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryUserDenomDepositRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserDenomDepositRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserDenomDepositRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserAcc) > 0 {
		i -= len(m.UserAcc)
		copy(dAtA[i:], m.UserAcc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAcc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserDenomDepositResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserDenomDepositResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserDenomDepositResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserDepositRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserDepositRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserDepositRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserAcc) > 0 {
		i -= len(m.UserAcc)
		copy(dAtA[i:], m.UserAcc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAcc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserDepositResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserDepositResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserDepositResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coins.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryUserClaimRewardsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserClaimRewardsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserClaimRewardsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UserAcc) > 0 {
		i -= len(m.UserAcc)
		copy(dAtA[i:], m.UserAcc)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAcc)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUserClaimRewardsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUserClaimRewardsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUserClaimRewardsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coins.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryWithdrawableRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWithdrawableRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWithdrawableRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UserAccount) > 0 {
		i -= len(m.UserAccount)
		copy(dAtA[i:], m.UserAccount)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.UserAccount)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryWithdrawableResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryWithdrawableResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryWithdrawableResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryUserDenomDepositRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAcc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserDenomDepositResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	return n
}

func (m *QueryUserDepositRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAcc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserDepositResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Coins.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryUserClaimRewardsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAcc)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUserClaimRewardsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Coins.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryWithdrawableRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UserAccount)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryWithdrawableResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Coin.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserDenomDepositRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserDenomDepositRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserDenomDepositRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAcc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAcc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserDenomDepositResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserDenomDepositResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserDenomDepositResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserDepositRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserDepositRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserDepositRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAcc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAcc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserDepositResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserDepositResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserDepositResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coins.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserClaimRewardsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserClaimRewardsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserClaimRewardsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAcc", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAcc = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUserClaimRewardsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUserClaimRewardsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUserClaimRewardsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coins.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWithdrawableRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWithdrawableRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWithdrawableRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryWithdrawableResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryWithdrawableResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryWithdrawableResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
