[package]
name = "share-distributor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
schemars = { workspace = true }
cw20 = { workspace = true }
serde = { workspace = true }

# Quasar packages
quasar-traits = { version = "0.1.0", path = "../quasar-traits" }