#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/../.." ; pwd)" # Absolute path to project dir
pf_dir="${project_dir}/demos/packet-forwarder"
this_script="${pf_dir}/$(basename "${0}")"
run_dir="${pf_dir}/run"
reset_run="${RESET:-true}"

env_subst() {
  # shellcheck disable=SC2016
  python -c '
import os, sys
data = sys.stdin.read(65536)
for v in os.environ:
  data = data.replace("$%s" % v, os.environ[v])
  data = data.replace("${%s}" % v, os.environ[v])
sys.stdout.write(data) ; sys.stdout.flush()
'
}

# TODO make macos / darwin version of this
run_in_terminal_bg() {
  gnome-terminal -- "$@" &
}

osmosis() {
  (
    echo "running osmosis chain"

    cd "${project_dir}/../osmosis"

    local osmosis_dir="${run_dir}/osmosis"

    if [ "$reset_run" == true ] ; then
      rm -rf "$osmosis_dir"
    fi

    export home_dir="${osmosis_dir}/home"
    mkdir -p "$home_dir"

    cat "${pf_dir}/osmosis.yml" | env_subst >| "${osmosis_dir}/config.yml"

    ignite chain serve --config "${osmosis_dir}/config.yml" --reset-once
  )
}

run_quasar_chain() {
  (
    local name="$1" ; shift
    local chain_dir="${run_dir}/${name}"

    echo "running ${name} chain"

    cd "$project_dir"

    if [ "$reset_run" == true ] ; then
      rm -rf "$chain_dir"
    fi

    export home_dir="${chain_dir}/home"
    mkdir -p "$home_dir"

    cat "${pf_dir}/${name}.yml" | env_subst >| "${chain_dir}/config.yml"

    ignite chain serve --config "${chain_dir}/config.yml" --reset-once
  )
}

quasar() { run_quasar_chain "quasar" ; }
cosmos() { run_quasar_chain "cosmos" ; }

all() {
  rm -rf ~/.ignite/

  run_in_terminal_bg "$this_script" osmosis
  sleep 1
  run_in_terminal_bg "$this_script" quasar
  sleep 1
  run_in_terminal_bg "$this_script" cosmos

  wait
}

test -d "${project_dir}/../osmosis" || ( echo "osmosis dir not found" && false )

"$@"
