[package]
authors = ["Nikita (rizz) <nj18@nyu.edu>"]
edition = "2021"
name = "merkle-incentives"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
codegen-units = 1
debug = false
debug-assertions = false
incremental = false
lto = true
opt-level = 3
overflow-checks = true
panic = 'abort'
rpath = false

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[package.metadata.scripts]
optimize = """docker run --rm -v "$(pwd)":/code \
  --mount type=volume,source="$(basename "$(pwd)")_cache",target=/target \
  --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry \
  cosmwasm/optimizer:0.15.0
"""

[dependencies]
base64 = "0.22.0"
cosmwasm-schema = "1.5.3"
cosmwasm-std = "1.5.3"
cw-storage-plus = "1.1.0"
cw2 = "1.1.1"
rs_merkle = { version = "1.4.2", default-features = false }
schemars = "0.8.15"
serde = {version = "1.0.189", default-features = false, features = ["derive"]}
serde-json-wasm = "1.0.1"
thiserror = {version = "1.0.49"}

[dev-dependencies]
osmosis-test-tube = "22.1.0"
