#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir
build_dir="${BUILD_DIR:-"${project_dir}/build"}"

mkdir -p "$build_dir"

build_with_tags() {
  go build -tags "$@" -o "${build_dir}/quasarnoded" "${project_dir}/cmd/quasarnoded"
}

build_dev() {
  build_with_tags "test"
}

install_with_tags() {
  go install -tags "$@" "${project_dir}/cmd/quasarnoded"
}

install_dev() {
  install_with_tags "test"
}

(
  cd "$project_dir"

  go mod download

  "$@"
)
