#!/usr/bin/env bash

set -Cue -o pipefail
set -o xtrace

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir
build_dir="${BUILD_DIR:-"${project_dir}/build"}"

mkdir -p "$build_dir"

build_with_tags() {
  go build -tags "$@" -o "${build_dir}/quasarnoded" "${project_dir}/cmd/quasarnoded"
}

build_dev() {
  go build -gcflags='all=-N -l' -tags "test" -o "${build_dir}/quasarnoded" "${project_dir}/cmd/quasarnoded"
  # build_with_tags "test"
}

install_with_tags() {
  go install -tags "$@" "${project_dir}/cmd/quasarnoded"
}

install_dev() {
  ## -gcflags='all=-N -l' is added to have debug symbols in the binary
  go install -gcflags='all=-N -l' -tags "test" "${project_dir}/cmd/quasarnoded" 
  #install_with_tags "test"
}

(
  cd "$project_dir"

  go mod download

  "$@"
)
