#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir
build_dir="${BUILD_DIR:-"${project_dir}/build"}"
docs_dir="${build_dir}/docs"
out_dir="${docs_dir}/grpc-swagger-doc"
tmp_dir="${docs_dir}/proto"

# Get the path of the cosmos-sdk repo from go/pkg/mod
locate_cosmos_sdk_dir() {
  go list -f "{{ .Dir }}" -m github.com/cosmos/cosmos-sdk
}

# Collect all proto dirs
collect_proto_dirs() {
  find "$@" -path -prune -o -name "*.proto" -print0 | xargs -0 -n1 dirname | sort | uniq
}

rm -rf "$out_dir"
mkdir -p "$docs_dir" "$tmp_dir" "$out_dir"
trap "rm -rf ${tmp_dir}" 0

cosmos_sdk_dir="$(locate_cosmos_sdk_dir)"

while read -r proto_dir <&3 ; do
  query_file="$(find "${proto_dir}" -maxdepth 1 \( -name 'query.proto' -o -name 'service.proto' \))"
  if [[ ! -z "$query_file" ]]; then
    protoc \
      -I "${project_dir}/proto" \
      -I "${cosmos_sdk_dir}/third_party/proto" \
      -I "${cosmos_sdk_dir}/proto" \
      "$query_file" \
      --swagger_out "$tmp_dir" \
      --swagger_opt logtostderr=true \
      --swagger_opt fqn_for_swagger_name=true \
      --swagger_opt simple_operation_ids=true
  fi
done 3< <(collect_proto_dirs "${project_dir}/proto" "${cosmos_sdk_dir}/proto")

(
  cd "${project_dir}/docs/client"

  npm install
  OUT_FILE="${out_dir}/swagger.yaml" npm run build
)
