#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir
this_dir="${project_dir}/scripts"
this_script="${this_dir}/$(basename "${0}")"
run_dir="${project_dir}/run/localnet"

fail() {
  echo "$*"
  false
}

cmd_exists() {
  type "$1" >/dev/null 2>&1 || fail "command '${1}' not available"
}

gen_config() {
  local n="$1" ; shift

  "${project_dir}/build/quasarnoded" testnet -n "$n" -o "$run_dir"
}

for_all_nodes() {
  local cmd="$1" ; shift

  while IFS= read -r -d '' node_dir <&3 ; do
    "$cmd" "$node_dir" "$@"
  done 3< <(find "$run_dir" -type d -name "node*" -print0 | sort -z)
}

run_for_node() {
  local node_dir="$1" ; shift
  local home_dir="${node_dir}/home"
  local node_name="$(basename "${node_dir}")"

  test -d "$node_dir" || fail "node '${node_name}' not found"

  (
    cd "$node_dir"

    cmd() {
      "${home_dir}/cosmovisor/current/bin/quasarnoded" --home "$home_dir" --keyring-backend=test --from main "$@"
    }

    start() {
      (
        export DAEMON_NAME="quasarnoded"
        export DAEMON_HOME="$home_dir"
        export DAEMON_RESTART_AFTER_UPGRADE=true

        nohup cosmovisor run start --home "$home_dir" >| "quasarnoded.log" 2>&1 &
        echo "$!" >| "quasarnoded.pid"
      )
    }

    stop() {
      kill "$(cat "quasarnoded.pid" 2> /dev/null)" > /dev/null 2>&1 || true
      rm -f "quasarnoded.pid"
    }

    status() {
      if ps -p "$(cat "quasarnoded.pid" 2> /dev/null)" > /dev/null 2>&1 ; then
        echo "node '${node_name}' is running"
      else
        echo "node '${node_name}' is NOT running"
      fi
    }

    log() {
      tail -f "quasarnoded.log"
    }

    "$@"
  )
}

start_all() {
  for_all_nodes run_for_node start
}

stop_all() {
  for_all_nodes run_for_node stop
  killall "cosmovisor"
}

status_all() {
  for_all_nodes run_for_node status
}

node() {
  local id="$1" ; shift
  local node_dir="${run_dir}/node${id}"

  run_for_node "$node_dir" "$@"
}

install_binary() {
  local node_dir="$1" ; shift

  mkdir -p "${node_dir}/home/cosmovisor/genesis/bin"
  mkdir -p "${node_dir}/home/cosmovisor/upgrades"

  cp "${project_dir}/build/quasarnoded" "${node_dir}/home/cosmovisor/genesis/bin/quasarnoded"
}

install_binaries() {
  for_all_nodes install_binary
}

init_default_cluster() {
  gen_config 4
  install_binaries
}

cmd_exists nohup
cmd_exists killall
cmd_exists cosmovisor

"$@"
