#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir

(
  cd "$project_dir"

  ignite chain serve -c config.yml --reset-once -v
)
