#!/usr/bin/env bash

set -Cue -o pipefail

project_dir="$(cd "$(dirname "${0}")/.." ; pwd)" # Absolute path to project dir

(
  cd "$project_dir"

  mkdir -p run/quasar/home

  ignite chain serve -c config.yml --home run/quasar/home --reset-once -v
)
