[alias]
wasm = "build --release --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --example schema"
test-tube = "test --package cw-dex-router --lib -- --include-ignored test_tube:: --nocapture --test-threads=1"
test-tube-build = "build --release --lib --target  wasm32-unknown-unknown --target-dir ./test-tube-build"
