// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orion/ibc.proto

package types

import (
	fmt "fmt"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IbcTokenTransfer struct {
	SeqNo       uint64      `protobuf:"varint,1,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
	Destination string      `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Sender      string      `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	Receiver    string      `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	StartTime   time.Time   `protobuf:"bytes,5,opt,name=startTime,proto3,stdtime" json:"startTime"`
	EpochDay    uint64      `protobuf:"varint,6,opt,name=epochDay,proto3" json:"epochDay,omitempty"`
	Coin        types1.Coin `protobuf:"bytes,7,opt,name=coin,proto3" json:"coin"`
}

func (m *IbcTokenTransfer) Reset()         { *m = IbcTokenTransfer{} }
func (m *IbcTokenTransfer) String() string { return proto.CompactTextString(m) }
func (*IbcTokenTransfer) ProtoMessage()    {}
func (*IbcTokenTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe823dad405965a, []int{0}
}
func (m *IbcTokenTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcTokenTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcTokenTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcTokenTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcTokenTransfer.Merge(m, src)
}
func (m *IbcTokenTransfer) XXX_Size() int {
	return m.Size()
}
func (m *IbcTokenTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcTokenTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_IbcTokenTransfer proto.InternalMessageInfo

func (m *IbcTokenTransfer) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *IbcTokenTransfer) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *IbcTokenTransfer) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *IbcTokenTransfer) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *IbcTokenTransfer) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *IbcTokenTransfer) GetEpochDay() uint64 {
	if m != nil {
		return m.EpochDay
	}
	return 0
}

func (m *IbcTokenTransfer) GetCoin() types1.Coin {
	if m != nil {
		return m.Coin
	}
	return types1.Coin{}
}

type IbcIcaWithdraw struct {
	SeqNo        uint64      `protobuf:"varint,1,opt,name=seqNo,proto3" json:"seqNo,omitempty"`
	ExitEpochDay uint64      `protobuf:"varint,2,opt,name=exitEpochDay,proto3" json:"exitEpochDay,omitempty"`
	Coin         types1.Coin `protobuf:"bytes,3,opt,name=coin,proto3" json:"coin"`
}

func (m *IbcIcaWithdraw) Reset()         { *m = IbcIcaWithdraw{} }
func (m *IbcIcaWithdraw) String() string { return proto.CompactTextString(m) }
func (*IbcIcaWithdraw) ProtoMessage()    {}
func (*IbcIcaWithdraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_cbe823dad405965a, []int{1}
}
func (m *IbcIcaWithdraw) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcIcaWithdraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcIcaWithdraw.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcIcaWithdraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcIcaWithdraw.Merge(m, src)
}
func (m *IbcIcaWithdraw) XXX_Size() int {
	return m.Size()
}
func (m *IbcIcaWithdraw) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcIcaWithdraw.DiscardUnknown(m)
}

var xxx_messageInfo_IbcIcaWithdraw proto.InternalMessageInfo

func (m *IbcIcaWithdraw) GetSeqNo() uint64 {
	if m != nil {
		return m.SeqNo
	}
	return 0
}

func (m *IbcIcaWithdraw) GetExitEpochDay() uint64 {
	if m != nil {
		return m.ExitEpochDay
	}
	return 0
}

func (m *IbcIcaWithdraw) GetCoin() types1.Coin {
	if m != nil {
		return m.Coin
	}
	return types1.Coin{}
}

func init() {
	proto.RegisterType((*IbcTokenTransfer)(nil), "quasarlabs.quasarnode.orion.IbcTokenTransfer")
	proto.RegisterType((*IbcIcaWithdraw)(nil), "quasarlabs.quasarnode.orion.IbcIcaWithdraw")
}

func init() { proto.RegisterFile("orion/ibc.proto", fileDescriptor_cbe823dad405965a) }

var fileDescriptor_cbe823dad405965a = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x14, 0x5c, 0x6f, 0xb7, 0x4b, 0xeb, 0x22, 0x40, 0x51, 0x85, 0x42, 0x90, 0xb2, 0xd1, 0x9e, 0xf6,
	0x64, 0xab, 0xf4, 0x1f, 0x04, 0x90, 0xd8, 0x0b, 0x87, 0x28, 0x12, 0x12, 0x37, 0xdb, 0x79, 0xcd,
	0x5a, 0x34, 0x7e, 0xa9, 0xed, 0x2d, 0xed, 0x89, 0xbf, 0x50, 0x89, 0x3f, 0xd5, 0x63, 0x8f, 0x9c,
	0x00, 0xed, 0xfe, 0x11, 0x14, 0x67, 0x3f, 0xe0, 0xc0, 0xa1, 0x37, 0xcf, 0x9b, 0x79, 0xcf, 0xa3,
	0xd1, 0xd0, 0xe7, 0x68, 0x35, 0x1a, 0xae, 0xa5, 0x62, 0xad, 0x45, 0x8f, 0xd1, 0xeb, 0xab, 0xa5,
	0x70, 0xc2, 0x5e, 0x0a, 0xe9, 0x58, 0xff, 0x34, 0x58, 0x01, 0x0b, 0xb2, 0xe4, 0xb4, 0xc6, 0x1a,
	0x83, 0x8e, 0x77, 0xaf, 0x7e, 0x25, 0x49, 0x15, 0xba, 0x06, 0x1d, 0x97, 0xc2, 0x01, 0xbf, 0x3e,
	0x93, 0xe0, 0xc5, 0x19, 0x57, 0xa8, 0xcd, 0x86, 0x9f, 0xd4, 0x88, 0xf5, 0x25, 0xf0, 0x80, 0xe4,
	0xf2, 0x82, 0x7b, 0xdd, 0x80, 0xf3, 0xa2, 0x69, 0x7b, 0xc1, 0xf4, 0xfb, 0x90, 0xbe, 0x98, 0x4b,
	0x55, 0xe2, 0x17, 0x30, 0xa5, 0x15, 0xc6, 0x5d, 0x80, 0x8d, 0x4e, 0xe9, 0xa1, 0x83, 0xab, 0x8f,
	0x18, 0x93, 0x8c, 0xcc, 0x46, 0x45, 0x0f, 0xa2, 0x8c, 0x9e, 0x54, 0xe0, 0xbc, 0x36, 0xc2, 0x6b,
	0x34, 0xf1, 0x30, 0x23, 0xb3, 0xe3, 0xe2, 0xef, 0x51, 0xf4, 0x92, 0x8e, 0x1d, 0x98, 0x0a, 0x6c,
	0x7c, 0x10, 0xc8, 0x0d, 0x8a, 0x12, 0x7a, 0x64, 0x41, 0x81, 0xbe, 0x06, 0x1b, 0x8f, 0x02, 0xb3,
	0xc3, 0x51, 0x4e, 0x8f, 0x9d, 0x17, 0xd6, 0x97, 0xba, 0x81, 0xf8, 0x30, 0x23, 0xb3, 0x93, 0x37,
	0x09, 0xeb, 0x5d, 0xb3, 0xad, 0x6b, 0x56, 0x6e, 0x5d, 0xe7, 0x47, 0xf7, 0x3f, 0x27, 0x83, 0xbb,
	0x5f, 0x13, 0x52, 0xec, 0xd7, 0xba, 0xfb, 0xd0, 0xa2, 0x5a, 0xbc, 0x13, 0xb7, 0xf1, 0x38, 0x58,
	0xde, 0xe1, 0xe8, 0x9c, 0x8e, 0xba, 0x3c, 0xe2, 0x27, 0xe1, 0xf4, 0x2b, 0xd6, 0x07, 0xc6, 0xba,
	0xc0, 0xd8, 0x26, 0x30, 0xf6, 0x16, 0xb5, 0xc9, 0x47, 0xdd, 0xe5, 0x22, 0x88, 0xa7, 0xdf, 0xe8,
	0xb3, 0xb9, 0x54, 0x73, 0x25, 0x3e, 0x69, 0xbf, 0xa8, 0xac, 0xf8, 0xfa, 0x9f, 0x48, 0xa6, 0xf4,
	0x29, 0xdc, 0x68, 0xff, 0x7e, 0xfb, 0xf9, 0x30, 0x90, 0xff, 0xcc, 0x76, 0x06, 0x0e, 0x1e, 0x61,
	0x20, 0xff, 0x70, 0xbf, 0x4a, 0xc9, 0xc3, 0x2a, 0x25, 0xbf, 0x57, 0x29, 0xb9, 0x5b, 0xa7, 0x83,
	0x87, 0x75, 0x3a, 0xf8, 0xb1, 0x4e, 0x07, 0x9f, 0x59, 0xad, 0xfd, 0x62, 0x29, 0x99, 0xc2, 0x86,
	0xef, 0xfb, 0xc2, 0xf7, 0x7d, 0xe1, 0x37, 0xbc, 0x2f, 0x96, 0xbf, 0x6d, 0xc1, 0xc9, 0x71, 0x08,
	0xf1, 0xfc, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xcb, 0x37, 0xdd, 0x6e, 0x02, 0x00, 0x00,
}

func (m *IbcTokenTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcTokenTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcTokenTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIbc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.EpochDay != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.EpochDay))
		i--
		dAtA[i] = 0x30
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintIbc(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Destination) > 0 {
		i -= len(m.Destination)
		copy(dAtA[i:], m.Destination)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.Destination)))
		i--
		dAtA[i] = 0x12
	}
	if m.SeqNo != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.SeqNo))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *IbcIcaWithdraw) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcIcaWithdraw) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcIcaWithdraw) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Coin.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIbc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.ExitEpochDay != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.ExitEpochDay))
		i--
		dAtA[i] = 0x10
	}
	if m.SeqNo != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.SeqNo))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintIbc(dAtA []byte, offset int, v uint64) int {
	offset -= sovIbc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IbcTokenTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SeqNo != 0 {
		n += 1 + sovIbc(uint64(m.SeqNo))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovIbc(uint64(l))
	if m.EpochDay != 0 {
		n += 1 + sovIbc(uint64(m.EpochDay))
	}
	l = m.Coin.Size()
	n += 1 + l + sovIbc(uint64(l))
	return n
}

func (m *IbcIcaWithdraw) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SeqNo != 0 {
		n += 1 + sovIbc(uint64(m.SeqNo))
	}
	if m.ExitEpochDay != 0 {
		n += 1 + sovIbc(uint64(m.ExitEpochDay))
	}
	l = m.Coin.Size()
	n += 1 + l + sovIbc(uint64(l))
	return n
}

func sovIbc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIbc(x uint64) (n int) {
	return sovIbc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IbcTokenTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcTokenTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcTokenTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqNo", wireType)
			}
			m.SeqNo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeqNo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDay", wireType)
			}
			m.EpochDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcIcaWithdraw) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcIcaWithdraw: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcIcaWithdraw: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SeqNo", wireType)
			}
			m.SeqNo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SeqNo |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitEpochDay", wireType)
			}
			m.ExitEpochDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExitEpochDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIbc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIbc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIbc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIbc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIbc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIbc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIbc = fmt.Errorf("proto: unexpected end of group")
)
