// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orion/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	PerfFeePer         github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=perf_fee_per,json=perfFeePer,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"perf_fee_per" yaml:"perf_fee_per"`
	MgmtFeePer         github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=mgmt_fee_per,json=mgmtFeePer,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"mgmt_fee_per" yaml:"mgmt_fee_per"`
	LpEpochId          string                                 `protobuf:"bytes,3,opt,name=lp_epoch_id,json=lpEpochId,proto3" json:"lp_epoch_id,omitempty" yaml:"lp_epoch_id"`
	DestinationChainId string                                 `protobuf:"bytes,4,opt,name=destination_chain_id,json=destinationChainId,proto3" json:"destination_chain_id,omitempty" yaml:"destination_chainid"`
	Enabled            bool                                   `protobuf:"varint,5,opt,name=enabled,proto3" json:"enabled,omitempty" yaml:"enabled,omitempty"`
	WhiteListedPools   []uint64                               `protobuf:"varint,6,rep,packed,name=white_listed_pools,json=whiteListedPools,proto3" json:"white_listed_pools,omitempty" yaml:"white_listed_pools"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bb3b70a736f4f4, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLpEpochId() string {
	if m != nil {
		return m.LpEpochId
	}
	return ""
}

func (m *Params) GetDestinationChainId() string {
	if m != nil {
		return m.DestinationChainId
	}
	return ""
}

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *Params) GetWhiteListedPools() []uint64 {
	if m != nil {
		return m.WhiteListedPools
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "abag.quasarnode.orion.Params")
}

func init() { proto.RegisterFile("orion/params.proto", fileDescriptor_76bb3b70a736f4f4) }

var fileDescriptor_76bb3b70a736f4f4 = []byte{
	// 413 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x6f, 0xd4, 0x30,
	0x14, 0xc6, 0x13, 0xae, 0x1c, 0xad, 0x61, 0x40, 0xa6, 0xa0, 0x50, 0x41, 0x7c, 0xca, 0x80, 0x6e,
	0x80, 0x64, 0x40, 0xea, 0xd0, 0x31, 0x50, 0xa4, 0x0a, 0x86, 0x53, 0x46, 0x96, 0xc8, 0x89, 0x5f,
	0x13, 0x8b, 0x38, 0x36, 0xb1, 0x2b, 0xb8, 0xff, 0x82, 0x91, 0xb1, 0x7f, 0x4e, 0xc7, 0x8e, 0x88,
	0x21, 0x42, 0x77, 0x0b, 0x73, 0xf8, 0x07, 0x90, 0x9d, 0x03, 0x22, 0x75, 0x64, 0x4a, 0xde, 0xf7,
	0xbe, 0xf7, 0xfb, 0xa4, 0xe4, 0x43, 0x58, 0x76, 0x5c, 0xb6, 0x89, 0xa2, 0x1d, 0x15, 0x3a, 0x56,
	0x9d, 0x34, 0x12, 0x3f, 0xa4, 0x05, 0xad, 0xe2, 0x8f, 0x17, 0x54, 0xd3, 0xae, 0x95, 0x0c, 0x62,
	0xe7, 0x39, 0x3a, 0xac, 0x64, 0x25, 0x9d, 0x23, 0xb1, 0x6f, 0xa3, 0x39, 0xfa, 0x35, 0x43, 0xf3,
	0x95, 0xbb, 0xc6, 0x15, 0xba, 0xa7, 0xa0, 0x3b, 0xcf, 0xcf, 0x01, 0x72, 0x05, 0x5d, 0xe0, 0x2f,
	0xfc, 0xe5, 0x41, 0x7a, 0x7a, 0xd5, 0x13, 0xef, 0x7b, 0x4f, 0x9e, 0x55, 0xdc, 0xd4, 0x17, 0x45,
	0x5c, 0x4a, 0x91, 0x94, 0x52, 0x0b, 0xa9, 0x77, 0x8f, 0x17, 0x9a, 0x7d, 0x48, 0xcc, 0x5a, 0x81,
	0x8e, 0x5f, 0x43, 0x39, 0xf4, 0xe4, 0xc1, 0x9a, 0x8a, 0xe6, 0x24, 0x9a, 0xb2, 0xa2, 0x0c, 0xd9,
	0xf1, 0x0d, 0xc0, 0x0a, 0x3a, 0x1b, 0x24, 0x2a, 0x61, 0xfe, 0x06, 0xdd, 0xfa, 0xbf, 0xa0, 0x29,
	0x2b, 0xca, 0x90, 0x1d, 0x77, 0x41, 0xc7, 0xe8, 0x6e, 0xa3, 0x72, 0x50, 0xb2, 0xac, 0x73, 0xce,
	0x82, 0x99, 0xcb, 0x79, 0x34, 0xf4, 0x04, 0x8f, 0x97, 0x93, 0x65, 0x94, 0x1d, 0x34, 0xea, 0xd4,
	0x0e, 0x67, 0x0c, 0xaf, 0xd0, 0x21, 0x03, 0x6d, 0x78, 0x4b, 0x0d, 0x97, 0x6d, 0x5e, 0xd6, 0x94,
	0xb7, 0x16, 0xb0, 0xe7, 0x00, 0xe1, 0xd0, 0x93, 0xa3, 0x11, 0x70, 0xc3, 0x65, 0x41, 0x78, 0xa2,
	0xbe, 0xb2, 0xe2, 0x19, 0xc3, 0xc7, 0xe8, 0x0e, 0xb4, 0xb4, 0x68, 0x80, 0x05, 0xb7, 0x17, 0xfe,
	0x72, 0x3f, 0x7d, 0x32, 0xf4, 0x24, 0x18, 0x21, 0xbb, 0xc5, 0x73, 0x29, 0xb8, 0x01, 0xa1, 0xcc,
	0x3a, 0xca, 0xfe, 0x98, 0xf1, 0x5b, 0x84, 0x3f, 0xd5, 0xdc, 0x40, 0xde, 0x70, 0x6d, 0x80, 0xe5,
	0x4a, 0xca, 0x46, 0x07, 0xf3, 0xc5, 0x6c, 0xb9, 0x97, 0x3e, 0x1d, 0x7a, 0xf2, 0x78, 0x44, 0xdc,
	0xf4, 0x44, 0xd9, 0x7d, 0x27, 0xbe, 0x73, 0xda, 0xca, 0x4a, 0x27, 0xfb, 0x5f, 0x2f, 0x89, 0xf7,
	0xf3, 0x92, 0xf8, 0x69, 0x7a, 0xb5, 0x09, 0xfd, 0xeb, 0x4d, 0xe8, 0xff, 0xd8, 0x84, 0xfe, 0x97,
	0x6d, 0xe8, 0x5d, 0x6f, 0x43, 0xef, 0xdb, 0x36, 0xf4, 0xde, 0x2f, 0x27, 0x5f, 0xdf, 0xf6, 0x28,
	0xf9, 0xd7, 0xa3, 0xe4, 0x73, 0x32, 0xb6, 0xcd, 0xfd, 0x83, 0x62, 0xee, 0x0a, 0xf4, 0xf2, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x24, 0x89, 0x14, 0x83, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PerfFeePer.Equal(that1.PerfFeePer) {
		return false
	}
	if !this.MgmtFeePer.Equal(that1.MgmtFeePer) {
		return false
	}
	if this.LpEpochId != that1.LpEpochId {
		return false
	}
	if this.DestinationChainId != that1.DestinationChainId {
		return false
	}
	if this.Enabled != that1.Enabled {
		return false
	}
	if len(this.WhiteListedPools) != len(that1.WhiteListedPools) {
		return false
	}
	for i := range this.WhiteListedPools {
		if this.WhiteListedPools[i] != that1.WhiteListedPools[i] {
			return false
		}
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhiteListedPools) > 0 {
		dAtA2 := make([]byte, len(m.WhiteListedPools)*10)
		var j1 int
		for _, num := range m.WhiteListedPools {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintParams(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x32
	}
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.DestinationChainId) > 0 {
		i -= len(m.DestinationChainId)
		copy(dAtA[i:], m.DestinationChainId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.DestinationChainId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.LpEpochId) > 0 {
		i -= len(m.LpEpochId)
		copy(dAtA[i:], m.LpEpochId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LpEpochId)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.MgmtFeePer.Size()
		i -= size
		if _, err := m.MgmtFeePer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.PerfFeePer.Size()
		i -= size
		if _, err := m.PerfFeePer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PerfFeePer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MgmtFeePer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.LpEpochId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.DestinationChainId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	if len(m.WhiteListedPools) > 0 {
		l = 0
		for _, e := range m.WhiteListedPools {
			l += sovParams(uint64(e))
		}
		n += 1 + sovParams(uint64(l)) + l
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerfFeePer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerfFeePer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MgmtFeePer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MgmtFeePer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpEpochId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LpEpochId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DestinationChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DestinationChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 6:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.WhiteListedPools = append(m.WhiteListedPools, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParams
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParams
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.WhiteListedPools) == 0 {
					m.WhiteListedPools = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.WhiteListedPools = append(m.WhiteListedPools, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field WhiteListedPools", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
