// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orion/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	PerfFeePer github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=perf_fee_per,json=perfFeePer,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"perf_fee_per" yaml:"perf_fee_per"`
	MgmtFeePer github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=mgmt_fee_per,json=mgmtFeePer,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"mgmt_fee_per" yaml:"mgmt_fee_per"`
	LpEpochId  string                                 `protobuf:"bytes,3,opt,name=lp_epoch_id,json=lpEpochId,proto3" json:"lp_epoch_id,omitempty" yaml:"lp_epoch_id"`
	Enabled    bool                                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty" yaml:"enabled,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_76bb3b70a736f4f4, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetLpEpochId() string {
	if m != nil {
		return m.LpEpochId
	}
	return ""
}

func (m *Params) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "abag.quasarnode.orion.Params")
}

func init() { proto.RegisterFile("orion/params.proto", fileDescriptor_76bb3b70a736f4f4) }

var fileDescriptor_76bb3b70a736f4f4 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x93, 0x7e, 0x55, 0x3f, 0x6a, 0x98, 0xc2, 0x1f, 0x45, 0x08, 0x25, 0x55, 0x06, 0xd4,
	0x01, 0xe2, 0x01, 0xa9, 0x43, 0xc7, 0x88, 0x22, 0xb1, 0x55, 0x19, 0x59, 0x22, 0x27, 0xb9, 0x4d,
	0x23, 0xe2, 0x5e, 0xe3, 0xa4, 0x12, 0x7d, 0x0b, 0x46, 0x46, 0x1e, 0xa7, 0x63, 0x47, 0xc4, 0x10,
	0xa1, 0xf6, 0x0d, 0xfa, 0x04, 0x28, 0x4e, 0x80, 0xec, 0x4c, 0xf6, 0xd1, 0x3d, 0xe7, 0xfe, 0x74,
	0x75, 0x88, 0x81, 0x32, 0xc5, 0x05, 0x15, 0x4c, 0x32, 0x9e, 0xbb, 0x42, 0x62, 0x81, 0xc6, 0x29,
	0x0b, 0x59, 0xe2, 0x3e, 0x2d, 0x59, 0xce, 0xe4, 0x02, 0x63, 0x70, 0x95, 0xe7, 0xfc, 0x24, 0xc1,
	0x04, 0x95, 0x83, 0x56, 0xbf, 0xda, 0xec, 0x6c, 0x3a, 0xa4, 0x37, 0x55, 0x69, 0x23, 0x21, 0x47,
	0x02, 0xe4, 0x2c, 0x98, 0x01, 0x04, 0x02, 0xa4, 0xa9, 0x0f, 0xf4, 0x61, 0xdf, 0x9b, 0xac, 0x4b,
	0x5b, 0xfb, 0x28, 0xed, 0xcb, 0x24, 0x2d, 0xe6, 0xcb, 0xd0, 0x8d, 0x90, 0xd3, 0x08, 0x73, 0x8e,
	0x79, 0xf3, 0x5c, 0xe7, 0xf1, 0x23, 0x2d, 0x56, 0x02, 0x72, 0xf7, 0x16, 0xa2, 0x7d, 0x69, 0x1f,
	0xaf, 0x18, 0xcf, 0xc6, 0x4e, 0x7b, 0x97, 0xe3, 0x93, 0x4a, 0xde, 0x01, 0x4c, 0x41, 0x56, 0x20,
	0x9e, 0xf0, 0xe2, 0x07, 0xd4, 0xf9, 0x1b, 0xa8, 0xbd, 0xcb, 0xf1, 0x49, 0x25, 0x1b, 0xd0, 0x88,
	0x1c, 0x66, 0x22, 0x00, 0x81, 0xd1, 0x3c, 0x48, 0x63, 0xf3, 0x9f, 0xe2, 0x9c, 0xed, 0x4b, 0xdb,
	0xa8, 0x93, 0xad, 0xa1, 0xe3, 0xf7, 0x33, 0x31, 0xa9, 0xc4, 0x7d, 0x6c, 0x8c, 0xc8, 0x7f, 0x58,
	0xb0, 0x30, 0x83, 0xd8, 0xec, 0x0e, 0xf4, 0xe1, 0x81, 0x77, 0xb1, 0x2f, 0x6d, 0xb3, 0xce, 0x34,
	0x83, 0x2b, 0xe4, 0x69, 0x01, 0x5c, 0x14, 0x2b, 0xc7, 0xff, 0x36, 0x8f, 0xbb, 0xaf, 0x6f, 0xb6,
	0xe6, 0x79, 0xeb, 0xad, 0xa5, 0x6f, 0xb6, 0x96, 0xfe, 0xb9, 0xb5, 0xf4, 0x97, 0x9d, 0xa5, 0x6d,
	0x76, 0x96, 0xf6, 0xbe, 0xb3, 0xb4, 0x87, 0x61, 0xeb, 0xb4, 0xaa, 0x24, 0xfa, 0x5b, 0x12, 0x7d,
	0xa6, 0x75, 0x95, 0xea, 0xc0, 0xb0, 0xa7, 0xda, 0xb9, 0xf9, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x5d,
	0xbf, 0xc1, 0x82, 0xe0, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.LpEpochId) > 0 {
		i -= len(m.LpEpochId)
		copy(dAtA[i:], m.LpEpochId)
		i = encodeVarintParams(dAtA, i, uint64(len(m.LpEpochId)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size := m.MgmtFeePer.Size()
		i -= size
		if _, err := m.MgmtFeePer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.PerfFeePer.Size()
		i -= size
		if _, err := m.PerfFeePer.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.PerfFeePer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MgmtFeePer.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.LpEpochId)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.Enabled {
		n += 2
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerfFeePer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PerfFeePer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MgmtFeePer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MgmtFeePer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpEpochId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LpEpochId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
