// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: orion/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryReserveBalanceRequest struct {
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
}

func (m *QueryReserveBalanceRequest) Reset()         { *m = QueryReserveBalanceRequest{} }
func (m *QueryReserveBalanceRequest) String() string { return proto.CompactTextString(m) }
func (*QueryReserveBalanceRequest) ProtoMessage()    {}
func (*QueryReserveBalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{2}
}
func (m *QueryReserveBalanceRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReserveBalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReserveBalanceRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReserveBalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReserveBalanceRequest.Merge(m, src)
}
func (m *QueryReserveBalanceRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryReserveBalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReserveBalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReserveBalanceRequest proto.InternalMessageInfo

func (m *QueryReserveBalanceRequest) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

type QueryReserveBalanceResponse struct {
	Amount uint64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *QueryReserveBalanceResponse) Reset()         { *m = QueryReserveBalanceResponse{} }
func (m *QueryReserveBalanceResponse) String() string { return proto.CompactTextString(m) }
func (*QueryReserveBalanceResponse) ProtoMessage()    {}
func (*QueryReserveBalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{3}
}
func (m *QueryReserveBalanceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryReserveBalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryReserveBalanceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryReserveBalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryReserveBalanceResponse.Merge(m, src)
}
func (m *QueryReserveBalanceResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryReserveBalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryReserveBalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryReserveBalanceResponse proto.InternalMessageInfo

func (m *QueryReserveBalanceResponse) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type QueryGetLpPositionRequest struct {
	LpId uint64 `protobuf:"varint,1,opt,name=lpId,proto3" json:"lpId,omitempty"`
}

func (m *QueryGetLpPositionRequest) Reset()         { *m = QueryGetLpPositionRequest{} }
func (m *QueryGetLpPositionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLpPositionRequest) ProtoMessage()    {}
func (*QueryGetLpPositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{4}
}
func (m *QueryGetLpPositionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLpPositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLpPositionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLpPositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLpPositionRequest.Merge(m, src)
}
func (m *QueryGetLpPositionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLpPositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLpPositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLpPositionRequest proto.InternalMessageInfo

func (m *QueryGetLpPositionRequest) GetLpId() uint64 {
	if m != nil {
		return m.LpId
	}
	return 0
}

type QueryGetLpPositionResponse struct {
	LpPosition LpPosition `protobuf:"bytes,1,opt,name=LpPosition,proto3" json:"LpPosition"`
}

func (m *QueryGetLpPositionResponse) Reset()         { *m = QueryGetLpPositionResponse{} }
func (m *QueryGetLpPositionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLpPositionResponse) ProtoMessage()    {}
func (*QueryGetLpPositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{5}
}
func (m *QueryGetLpPositionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLpPositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLpPositionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLpPositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLpPositionResponse.Merge(m, src)
}
func (m *QueryGetLpPositionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLpPositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLpPositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLpPositionResponse proto.InternalMessageInfo

func (m *QueryGetLpPositionResponse) GetLpPosition() LpPosition {
	if m != nil {
		return m.LpPosition
	}
	return LpPosition{}
}

type QueryGetEpochLPInfoRequest struct {
	EpochDay uint64 `protobuf:"varint,1,opt,name=epochDay,proto3" json:"epochDay,omitempty"`
}

func (m *QueryGetEpochLPInfoRequest) Reset()         { *m = QueryGetEpochLPInfoRequest{} }
func (m *QueryGetEpochLPInfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetEpochLPInfoRequest) ProtoMessage()    {}
func (*QueryGetEpochLPInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{6}
}
func (m *QueryGetEpochLPInfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEpochLPInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEpochLPInfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEpochLPInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEpochLPInfoRequest.Merge(m, src)
}
func (m *QueryGetEpochLPInfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEpochLPInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEpochLPInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEpochLPInfoRequest proto.InternalMessageInfo

func (m *QueryGetEpochLPInfoRequest) GetEpochDay() uint64 {
	if m != nil {
		return m.EpochDay
	}
	return 0
}

type QueryGetEpochLPInfoResponse struct {
	EpochLPInfo EpochLPInfo `protobuf:"bytes,1,opt,name=EpochLPInfo,proto3" json:"EpochLPInfo"`
}

func (m *QueryGetEpochLPInfoResponse) Reset()         { *m = QueryGetEpochLPInfoResponse{} }
func (m *QueryGetEpochLPInfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetEpochLPInfoResponse) ProtoMessage()    {}
func (*QueryGetEpochLPInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{7}
}
func (m *QueryGetEpochLPInfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetEpochLPInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetEpochLPInfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetEpochLPInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetEpochLPInfoResponse.Merge(m, src)
}
func (m *QueryGetEpochLPInfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetEpochLPInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetEpochLPInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetEpochLPInfoResponse proto.InternalMessageInfo

func (m *QueryGetEpochLPInfoResponse) GetEpochLPInfo() EpochLPInfo {
	if m != nil {
		return m.EpochLPInfo
	}
	return EpochLPInfo{}
}

type QueryGetRewardCollectionRequest struct {
	EpochDay uint64 `protobuf:"varint,1,opt,name=epochDay,proto3" json:"epochDay,omitempty"`
}

func (m *QueryGetRewardCollectionRequest) Reset()         { *m = QueryGetRewardCollectionRequest{} }
func (m *QueryGetRewardCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRewardCollectionRequest) ProtoMessage()    {}
func (*QueryGetRewardCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{8}
}
func (m *QueryGetRewardCollectionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRewardCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRewardCollectionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRewardCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRewardCollectionRequest.Merge(m, src)
}
func (m *QueryGetRewardCollectionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRewardCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRewardCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRewardCollectionRequest proto.InternalMessageInfo

func (m *QueryGetRewardCollectionRequest) GetEpochDay() uint64 {
	if m != nil {
		return m.EpochDay
	}
	return 0
}

type QueryGetRewardCollectionResponse struct {
	RewardCollection RewardCollection `protobuf:"bytes,1,opt,name=RewardCollection,proto3" json:"RewardCollection"`
}

func (m *QueryGetRewardCollectionResponse) Reset()         { *m = QueryGetRewardCollectionResponse{} }
func (m *QueryGetRewardCollectionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRewardCollectionResponse) ProtoMessage()    {}
func (*QueryGetRewardCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{9}
}
func (m *QueryGetRewardCollectionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRewardCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRewardCollectionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRewardCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRewardCollectionResponse.Merge(m, src)
}
func (m *QueryGetRewardCollectionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRewardCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRewardCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRewardCollectionResponse proto.InternalMessageInfo

func (m *QueryGetRewardCollectionResponse) GetRewardCollection() RewardCollection {
	if m != nil {
		return m.RewardCollection
	}
	return RewardCollection{}
}

type QueryGetLpStatRequest struct {
	EpochDay uint64 `protobuf:"varint,1,opt,name=epochDay,proto3" json:"epochDay,omitempty"`
}

func (m *QueryGetLpStatRequest) Reset()         { *m = QueryGetLpStatRequest{} }
func (m *QueryGetLpStatRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetLpStatRequest) ProtoMessage()    {}
func (*QueryGetLpStatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{10}
}
func (m *QueryGetLpStatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLpStatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLpStatRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLpStatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLpStatRequest.Merge(m, src)
}
func (m *QueryGetLpStatRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLpStatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLpStatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLpStatRequest proto.InternalMessageInfo

func (m *QueryGetLpStatRequest) GetEpochDay() uint64 {
	if m != nil {
		return m.EpochDay
	}
	return 0
}

type QueryGetLpStatResponse struct {
	LpStat LpStat `protobuf:"bytes,1,opt,name=LpStat,proto3" json:"LpStat"`
}

func (m *QueryGetLpStatResponse) Reset()         { *m = QueryGetLpStatResponse{} }
func (m *QueryGetLpStatResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetLpStatResponse) ProtoMessage()    {}
func (*QueryGetLpStatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_92ba854d0f1d3172, []int{11}
}
func (m *QueryGetLpStatResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetLpStatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetLpStatResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetLpStatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetLpStatResponse.Merge(m, src)
}
func (m *QueryGetLpStatResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetLpStatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetLpStatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetLpStatResponse proto.InternalMessageInfo

func (m *QueryGetLpStatResponse) GetLpStat() LpStat {
	if m != nil {
		return m.LpStat
	}
	return LpStat{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "abag.quasarnode.orion.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "abag.quasarnode.orion.QueryParamsResponse")
	proto.RegisterType((*QueryReserveBalanceRequest)(nil), "abag.quasarnode.orion.QueryReserveBalanceRequest")
	proto.RegisterType((*QueryReserveBalanceResponse)(nil), "abag.quasarnode.orion.QueryReserveBalanceResponse")
	proto.RegisterType((*QueryGetLpPositionRequest)(nil), "abag.quasarnode.orion.QueryGetLpPositionRequest")
	proto.RegisterType((*QueryGetLpPositionResponse)(nil), "abag.quasarnode.orion.QueryGetLpPositionResponse")
	proto.RegisterType((*QueryGetEpochLPInfoRequest)(nil), "abag.quasarnode.orion.QueryGetEpochLPInfoRequest")
	proto.RegisterType((*QueryGetEpochLPInfoResponse)(nil), "abag.quasarnode.orion.QueryGetEpochLPInfoResponse")
	proto.RegisterType((*QueryGetRewardCollectionRequest)(nil), "abag.quasarnode.orion.QueryGetRewardCollectionRequest")
	proto.RegisterType((*QueryGetRewardCollectionResponse)(nil), "abag.quasarnode.orion.QueryGetRewardCollectionResponse")
	proto.RegisterType((*QueryGetLpStatRequest)(nil), "abag.quasarnode.orion.QueryGetLpStatRequest")
	proto.RegisterType((*QueryGetLpStatResponse)(nil), "abag.quasarnode.orion.QueryGetLpStatResponse")
}

func init() { proto.RegisterFile("orion/query.proto", fileDescriptor_92ba854d0f1d3172) }

var fileDescriptor_92ba854d0f1d3172 = []byte{
	// 734 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x95, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x1b, 0xb4, 0x15, 0xf0, 0x24, 0x04, 0xde, 0x0f, 0xb6, 0xc0, 0xba, 0x61, 0x8d, 0x31,
	0xaa, 0x91, 0xac, 0x9d, 0x18, 0x48, 0x88, 0x4b, 0x01, 0x4d, 0x43, 0x3b, 0x8c, 0x20, 0x0e, 0x70,
	0xa9, 0xdc, 0xd6, 0xcb, 0x22, 0xa5, 0x71, 0x16, 0xbb, 0x83, 0x09, 0xed, 0xc2, 0x81, 0x1b, 0x12,
	0x12, 0x67, 0x2e, 0xfc, 0x03, 0x9c, 0xf8, 0x1f, 0x76, 0x63, 0x12, 0x17, 0x4e, 0x08, 0x6d, 0xfc,
	0x21, 0xa8, 0xf6, 0xcb, 0x9a, 0xa6, 0xcd, 0xda, 0xdd, 0x62, 0xfb, 0x7d, 0xdf, 0xfb, 0xc4, 0x7e,
	0x5f, 0x1b, 0x5d, 0xe3, 0x91, 0xc7, 0x03, 0x7b, 0xb7, 0xc5, 0xa2, 0x7d, 0x2b, 0x8c, 0xb8, 0xe4,
	0x78, 0x92, 0xd6, 0xa8, 0x6b, 0xed, 0xb6, 0xa8, 0xa0, 0x51, 0xc0, 0x1b, 0xcc, 0x52, 0x21, 0xe6,
	0x84, 0xcb, 0x5d, 0xae, 0x22, 0xec, 0xf6, 0x97, 0x0e, 0x36, 0x6f, 0xba, 0x9c, 0xbb, 0x3e, 0xb3,
	0x69, 0xe8, 0xd9, 0x34, 0x08, 0xb8, 0xa4, 0xd2, 0xe3, 0x81, 0x80, 0xd5, 0x62, 0x9d, 0x8b, 0x26,
	0x17, 0x76, 0x8d, 0x0a, 0xa6, 0x6b, 0xd8, 0x7b, 0xa5, 0x1a, 0x93, 0xb4, 0x64, 0x87, 0xd4, 0xf5,
	0x02, 0x15, 0x0c, 0xb1, 0x58, 0x93, 0x84, 0x34, 0xa2, 0xcd, 0x58, 0x7f, 0x5d, 0xcf, 0xf9, 0x61,
	0x35, 0xe4, 0xc2, 0x4b, 0x04, 0xcf, 0xe8, 0x05, 0x16, 0xf2, 0xfa, 0x4e, 0xd5, 0x0f, 0xab, 0x5e,
	0xb0, 0x1d, 0x13, 0xcd, 0xea, 0xa5, 0x88, 0xbd, 0xa5, 0x51, 0xa3, 0x5a, 0xe7, 0xbe, 0xcf, 0xea,
	0x09, 0xe5, 0xb4, 0x5e, 0x6e, 0x09, 0x16, 0xa5, 0x84, 0xe3, 0xa7, 0xc5, 0x84, 0xa4, 0x52, 0x4f,
	0x92, 0x09, 0x84, 0x5f, 0xb4, 0xb9, 0xb7, 0x14, 0x96, 0xc3, 0x76, 0x5b, 0x4c, 0x48, 0xe2, 0xa0,
	0xf1, 0xae, 0x59, 0x11, 0xf2, 0x40, 0x30, 0xfc, 0x08, 0xe5, 0x35, 0xfe, 0xb4, 0x31, 0x6f, 0x2c,
	0x8d, 0x95, 0x67, 0xad, 0xbe, 0x5b, 0x69, 0x69, 0x59, 0x65, 0xe4, 0xf0, 0xcf, 0x5c, 0xce, 0x01,
	0x09, 0x29, 0x23, 0x53, 0xe5, 0x74, 0x98, 0x60, 0xd1, 0x1e, 0xab, 0x50, 0x9f, 0x06, 0x75, 0x06,
	0x15, 0xf1, 0x04, 0x1a, 0x6d, 0xb0, 0x80, 0x37, 0x55, 0xe6, 0xcb, 0x8e, 0x1e, 0x90, 0xfb, 0xe8,
	0x46, 0x5f, 0x0d, 0xf0, 0x4c, 0xa1, 0x3c, 0x6d, 0xf2, 0x56, 0x20, 0x95, 0x6a, 0xc4, 0x81, 0x11,
	0xb1, 0xd1, 0x8c, 0x92, 0xad, 0x33, 0xb9, 0x19, 0x6e, 0xc1, 0xce, 0xc6, 0x95, 0x30, 0x1a, 0xf1,
	0xc3, 0x8d, 0x06, 0x48, 0xd4, 0x37, 0x61, 0xc0, 0x96, 0x12, 0x40, 0x99, 0x75, 0x84, 0x3a, 0xb3,
	0xf0, 0xeb, 0xb7, 0x32, 0x7e, 0xbd, 0x13, 0x08, 0xbf, 0x9f, 0x90, 0x92, 0x87, 0x9d, 0x32, 0xcf,
	0xda, 0x27, 0xbb, 0xb9, 0xb5, 0x11, 0x6c, 0xf3, 0x18, 0xcc, 0x44, 0x97, 0xd4, 0x79, 0x3f, 0xa5,
	0xfb, 0x00, 0x77, 0x3a, 0x26, 0x1e, 0x6c, 0x44, 0x5a, 0x09, 0x84, 0xcf, 0xd1, 0x58, 0x62, 0x1a,
	0x10, 0x49, 0x06, 0x62, 0x22, 0x12, 0x18, 0x93, 0x62, 0xf2, 0x18, 0xcd, 0xc5, 0xa5, 0x1c, 0xd5,
	0x63, 0x4f, 0x4e, 0x5b, 0x6c, 0x18, 0xd2, 0x03, 0x34, 0x9f, 0x2d, 0x07, 0xdc, 0xd7, 0xe8, 0x6a,
	0x7a, 0x0d, 0x98, 0xef, 0x64, 0x30, 0xa7, 0xc3, 0x01, 0xbc, 0x27, 0x0d, 0x59, 0x45, 0x93, 0x9d,
	0x93, 0x7c, 0x29, 0xa9, 0x1c, 0x86, 0xf9, 0x15, 0x9a, 0x4a, 0x8b, 0x3a, 0x1d, 0xaf, 0x67, 0x06,
	0x74, 0xbc, 0x0e, 0x8a, 0x3b, 0x5e, 0x8f, 0xca, 0x3f, 0x2f, 0xa2, 0x51, 0x95, 0x17, 0x7f, 0x34,
	0x50, 0x5e, 0x9b, 0x02, 0xdf, 0xcd, 0xc8, 0xd0, 0xeb, 0x42, 0xb3, 0x38, 0x4c, 0xa8, 0x06, 0x25,
	0xb7, 0x3f, 0xfc, 0xfa, 0xf7, 0xe5, 0xc2, 0x1c, 0x9e, 0xb5, 0xdb, 0x1a, 0xbb, 0xa3, 0xb1, 0x93,
	0xd7, 0x0e, 0xfe, 0x6e, 0xa0, 0x2b, 0xdd, 0x66, 0xc2, 0xa5, 0xb3, 0xaa, 0xf4, 0x35, 0xab, 0x59,
	0x3e, 0x8f, 0x04, 0x00, 0xd7, 0x14, 0xe0, 0x0a, 0xb6, 0x32, 0x00, 0x23, 0x2d, 0xab, 0xd6, 0xb4,
	0xce, 0x7e, 0xaf, 0x6e, 0x80, 0x03, 0xfc, 0xd5, 0x48, 0xba, 0x0f, 0xaf, 0x9c, 0x55, 0xba, 0x9f,
	0xdf, 0xcd, 0xd2, 0x39, 0x14, 0xc0, 0x5a, 0x54, 0xac, 0x0b, 0x98, 0x64, 0xb0, 0x26, 0xee, 0x6b,
	0xfc, 0xcd, 0xe8, 0xf2, 0x1e, 0x1e, 0x54, 0xae, 0xd7, 0xf8, 0x67, 0x6f, 0x67, 0x7f, 0xc7, 0x93,
	0x65, 0x85, 0xb8, 0x88, 0x17, 0x32, 0x10, 0xbb, 0x5e, 0x0e, 0xfc, 0xc3, 0xe8, 0x75, 0x1c, 0x5e,
	0x1b, 0x50, 0x36, 0xc3, 0xfd, 0xe6, 0x83, 0x73, 0xeb, 0x80, 0x79, 0x45, 0x31, 0x17, 0xf1, 0x52,
	0x66, 0x0b, 0xa4, 0x9e, 0x34, 0xfc, 0xc9, 0x88, 0xfd, 0x87, 0x97, 0x07, 0x1e, 0x63, 0xc2, 0xed,
	0xe6, 0xbd, 0x21, 0xa3, 0x81, 0x6c, 0x51, 0x91, 0xcd, 0xe3, 0x42, 0xf6, 0x81, 0xb7, 0xdf, 0xcc,
	0x4a, 0xe5, 0xf0, 0xb8, 0x60, 0x1c, 0x1d, 0x17, 0x8c, 0xbf, 0xc7, 0x05, 0xe3, 0xf3, 0x49, 0x21,
	0x77, 0x74, 0x52, 0xc8, 0xfd, 0x3e, 0x29, 0xe4, 0xde, 0x2c, 0xb9, 0x9e, 0xdc, 0x69, 0xd5, 0xac,
	0x3a, 0x6f, 0xf6, 0xe4, 0x78, 0x07, 0x59, 0xe4, 0x7e, 0xc8, 0x44, 0x2d, 0xaf, 0x1e, 0xde, 0xd5,
	0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0x10, 0x5b, 0x07, 0xd2, 0x9a, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of ReserveBalance items.
	ReserveBalance(ctx context.Context, in *QueryReserveBalanceRequest, opts ...grpc.CallOption) (*QueryReserveBalanceResponse, error)
	// Queries a LpPosition by index.
	LpPosition(ctx context.Context, in *QueryGetLpPositionRequest, opts ...grpc.CallOption) (*QueryGetLpPositionResponse, error)
	// Queries a EpochLPInfo by index.
	EpochLPInfo(ctx context.Context, in *QueryGetEpochLPInfoRequest, opts ...grpc.CallOption) (*QueryGetEpochLPInfoResponse, error)
	// Queries a RewardCollection by index.
	RewardCollection(ctx context.Context, in *QueryGetRewardCollectionRequest, opts ...grpc.CallOption) (*QueryGetRewardCollectionResponse, error)
	// Queries a LpStat by index.
	LpStat(ctx context.Context, in *QueryGetLpStatRequest, opts ...grpc.CallOption) (*QueryGetLpStatResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ReserveBalance(ctx context.Context, in *QueryReserveBalanceRequest, opts ...grpc.CallOption) (*QueryReserveBalanceResponse, error) {
	out := new(QueryReserveBalanceResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/ReserveBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LpPosition(ctx context.Context, in *QueryGetLpPositionRequest, opts ...grpc.CallOption) (*QueryGetLpPositionResponse, error) {
	out := new(QueryGetLpPositionResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/LpPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) EpochLPInfo(ctx context.Context, in *QueryGetEpochLPInfoRequest, opts ...grpc.CallOption) (*QueryGetEpochLPInfoResponse, error) {
	out := new(QueryGetEpochLPInfoResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/EpochLPInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RewardCollection(ctx context.Context, in *QueryGetRewardCollectionRequest, opts ...grpc.CallOption) (*QueryGetRewardCollectionResponse, error) {
	out := new(QueryGetRewardCollectionResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/RewardCollection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) LpStat(ctx context.Context, in *QueryGetLpStatRequest, opts ...grpc.CallOption) (*QueryGetLpStatResponse, error) {
	out := new(QueryGetLpStatResponse)
	err := c.cc.Invoke(ctx, "/abag.quasarnode.orion.Query/LpStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of ReserveBalance items.
	ReserveBalance(context.Context, *QueryReserveBalanceRequest) (*QueryReserveBalanceResponse, error)
	// Queries a LpPosition by index.
	LpPosition(context.Context, *QueryGetLpPositionRequest) (*QueryGetLpPositionResponse, error)
	// Queries a EpochLPInfo by index.
	EpochLPInfo(context.Context, *QueryGetEpochLPInfoRequest) (*QueryGetEpochLPInfoResponse, error)
	// Queries a RewardCollection by index.
	RewardCollection(context.Context, *QueryGetRewardCollectionRequest) (*QueryGetRewardCollectionResponse, error)
	// Queries a LpStat by index.
	LpStat(context.Context, *QueryGetLpStatRequest) (*QueryGetLpStatResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ReserveBalance(ctx context.Context, req *QueryReserveBalanceRequest) (*QueryReserveBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveBalance not implemented")
}
func (*UnimplementedQueryServer) LpPosition(ctx context.Context, req *QueryGetLpPositionRequest) (*QueryGetLpPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LpPosition not implemented")
}
func (*UnimplementedQueryServer) EpochLPInfo(ctx context.Context, req *QueryGetEpochLPInfoRequest) (*QueryGetEpochLPInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EpochLPInfo not implemented")
}
func (*UnimplementedQueryServer) RewardCollection(ctx context.Context, req *QueryGetRewardCollectionRequest) (*QueryGetRewardCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RewardCollection not implemented")
}
func (*UnimplementedQueryServer) LpStat(ctx context.Context, req *QueryGetLpStatRequest) (*QueryGetLpStatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LpStat not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ReserveBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryReserveBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ReserveBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/ReserveBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ReserveBalance(ctx, req.(*QueryReserveBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LpPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLpPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LpPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/LpPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LpPosition(ctx, req.(*QueryGetLpPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_EpochLPInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetEpochLPInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).EpochLPInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/EpochLPInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).EpochLPInfo(ctx, req.(*QueryGetEpochLPInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RewardCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRewardCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RewardCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/RewardCollection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RewardCollection(ctx, req.(*QueryGetRewardCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_LpStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetLpStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).LpStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.quasarnode.orion.Query/LpStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).LpStat(ctx, req.(*QueryGetLpStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "abag.quasarnode.orion.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ReserveBalance",
			Handler:    _Query_ReserveBalance_Handler,
		},
		{
			MethodName: "LpPosition",
			Handler:    _Query_LpPosition_Handler,
		},
		{
			MethodName: "EpochLPInfo",
			Handler:    _Query_EpochLPInfo_Handler,
		},
		{
			MethodName: "RewardCollection",
			Handler:    _Query_RewardCollection_Handler,
		},
		{
			MethodName: "LpStat",
			Handler:    _Query_LpStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orion/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryReserveBalanceRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReserveBalanceRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReserveBalanceRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryReserveBalanceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryReserveBalanceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryReserveBalanceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLpPositionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLpPositionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLpPositionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.LpId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.LpId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLpPositionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLpPositionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLpPositionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LpPosition.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetEpochLPInfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEpochLPInfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEpochLPInfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochDay != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochDay))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetEpochLPInfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetEpochLPInfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetEpochLPInfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.EpochLPInfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetRewardCollectionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRewardCollectionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRewardCollectionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochDay != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochDay))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRewardCollectionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRewardCollectionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRewardCollectionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RewardCollection.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetLpStatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLpStatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLpStatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochDay != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.EpochDay))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetLpStatResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetLpStatResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetLpStatResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.LpStat.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryReserveBalanceRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryReserveBalanceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovQuery(uint64(m.Amount))
	}
	return n
}

func (m *QueryGetLpPositionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LpId != 0 {
		n += 1 + sovQuery(uint64(m.LpId))
	}
	return n
}

func (m *QueryGetLpPositionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LpPosition.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetEpochLPInfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochDay != 0 {
		n += 1 + sovQuery(uint64(m.EpochDay))
	}
	return n
}

func (m *QueryGetEpochLPInfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.EpochLPInfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetRewardCollectionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochDay != 0 {
		n += 1 + sovQuery(uint64(m.EpochDay))
	}
	return n
}

func (m *QueryGetRewardCollectionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.RewardCollection.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetLpStatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.EpochDay != 0 {
		n += 1 + sovQuery(uint64(m.EpochDay))
	}
	return n
}

func (m *QueryGetLpStatResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.LpStat.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReserveBalanceRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReserveBalanceRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReserveBalanceRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryReserveBalanceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryReserveBalanceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryReserveBalanceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLpPositionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLpPositionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLpPositionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpId", wireType)
			}
			m.LpId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LpId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLpPositionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLpPositionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLpPositionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpPosition", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LpPosition.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEpochLPInfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEpochLPInfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEpochLPInfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDay", wireType)
			}
			m.EpochDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetEpochLPInfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetEpochLPInfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetEpochLPInfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLPInfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EpochLPInfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRewardCollectionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRewardCollectionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRewardCollectionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDay", wireType)
			}
			m.EpochDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRewardCollectionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRewardCollectionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRewardCollectionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardCollection", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardCollection.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLpStatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLpStatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLpStatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochDay", wireType)
			}
			m.EpochDay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochDay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetLpStatResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetLpStatResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetLpStatResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LpStat", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LpStat.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
