name: Store cargo build cache

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string

env:
  CARGO_TARGET_DIR: ~/target

jobs:
  store-build-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Restore dependencies
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.cache/cachepot
            ~/.cargo
            ~/go
            ~/target
          key: ${{ runner.os }}-cargo-${{ inputs.workspace }}-${{github.sha}}
          restore-keys: ${{ runner.os }}-cargo-${{ inputs.workspace }}
      - name: Install cachepot
        run: test -e ~/.cargo/bin/cachepot && echo "cachepot found -- skipping install" || cargo install --git https://github.com/paritytech/cachepot
      - name: Rust check
        run:  cargo check --all-targets --features test-tube
        working-directory: smart-contracts/${{ inputs.workspace }}
        env:
          RUSTC_WRAPPER: cachepot
      - name: Store dependencies
        uses: actions/cache/save@v4
        with:
          path: |
            ~/.cache/cachepot
            ~/.cargo
            ~/go
            ~/target
          key: ${{ runner.os }}-cargo-${{ inputs.workspace }}-${{github.sha}}
