name: Store cargo build cache (osmosis)

on:
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/**.rs'
      - 'smart-contracts/osmosis/**.toml'
  workflow_dispatch:

jobs:
  osmosis-build-cache:
    uses: ./.github/workflows/cargo_build_cache.yml
    with:
      workspace: osmosis
