name: Test dex router (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/dex-router-osmosis/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'contracts/dex-router-osmosis'
  test-tube:
    uses: ./.github/workflows/rust_test_tube.yml
    with:
      contract: 'dex-router-osmosis'
