name: Lint (Go)

# todo remove v3.x beafore merge to main
on:
  pull_request:
    branches:
      - main
      - v3.x
    paths-ignore:
      - 'smart-contracts/**'
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'smart-contracts/**'
      - '**.md'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

# This workflow makes x86_64 binaries for linux.
# TODO: add darwin later
jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
            Makefile
      - name: Setup Golang
        if: env.GIT_DIFF
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Display go version
        if: env.GIT_DIFF
        run: go version
      - name: Go lint
        if: env.GIT_DIFF
        run: make lint
