name: Test lst dex adapter (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/lst-dex-adapter-osmosis/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      contract: 'lst-dex-adapter-osmosis'
