name: Merkle Incentives

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/merkle-incentives/Cargo.toml'
      - 'smart-contracts/contracts/merkle-incentives/**.rs'
      - '.github/workflows/**.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/contracts/merkle-incentives/Cargo.toml'
      - 'smart-contracts/contracts/merkle-incentives/**.rs'
      - '.github/workflows/**.yml'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'contract/merkle-incentives'
  test-tube:
    uses: ./.github/workflows/rust_test_tube.yml
    with:
      contract: 'merkle-incentives'
