name: Merkle Incentives (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/contracts/merkle-incentives/Cargo.toml'
      - 'smart-contracts/osmosis/contracts/merkle-incentives/**.rs'
      - '.github/workflows/rust_basic.yml'
      - '.github/workflows/merkle_incentives_osmosis.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/contracts/merkle-incentives/Cargo.toml'
      - 'smart-contracts/osmosis/contracts/merkle-incentives/**.rs'
      - '.github/workflows/rust_basic.yml'
      - '.github/workflows/merkle_incentives_osmosis.yml'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'osmosis/contracts/merkle-incentives'
