name: Test quasar-types

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/packages/quasar-types/**'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'packages/quasar-types'
