name: Quasar Types

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/packages/quasar-types/**'
      - '.github/workflows/**.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/packages/quasar-types/**'
      - '.github/workflows/**.yml'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: 'packages/quasar-types'
