name: Range Middleware (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/contracts/range-middleware/Cargo.toml'
      - 'smart-contracts/osmosis/contracts/range-middleware/**.rs'
      - '.github/workflows/rust_basic.yml'
      - '.github/workflows/range_middleware_osmosis.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/contracts/range-middleware/Cargo.toml'
      - 'smart-contracts/osmosis/contracts/range-middleware/**.rs'
      - '.github/workflows/rust_basic.yml'
      - '.github/workflows/range_middleware_osmosis.yml'
  workflow_dispatch:

jobs:
  unit-test:
    uses: ./.github/workflows/rust_basic.yml
    with:
      target: contracts/range-middleware
      workspace: osmosis
