name: Unit Test (rust)

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      target:
        required: true
        type: string
      unit_tests:
        required: false
        default: true
        type: boolean

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust lint
        run:  cargo clippy --all-targets -- -D warnings
        working-directory: smart-contracts/${{ inputs.workspace }}
      - name: Rust format check
        run: cargo fmt --all -- --check
        working-directory: smart-contracts/${{ inputs.workspace }}/${{ inputs.target }}
      - if: inputs.unit_tests
        name: Run unit-tests
        run: cargo unit-test
        working-directory: smart-contracts/${{ inputs.workspace }}/${{ inputs.target }}
