name: Test Tube (osmosis)

on:
  pull_request:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/**/Cargo.toml'
      - 'smart-contracts/osmosis/**.rs'
      - '.github/workflows/test_tube.yml'
      - '.github/workflows/all_checks_osmosis.yml'
  push:
    branches:
      - main
    paths:
      - 'smart-contracts/osmosis/**/Cargo.toml'
      - 'smart-contracts/osmosis/**.rs'
      - '.github/workflows/test_tube.yml'
      - '.github/workflows/all_checks_osmosis.yml'
  workflow_dispatch:

jobs:
  post-merge:
    uses: ./.github/workflows/all_checks_osmosis.yml
    if: github.event_name == 'push'
    with:
      proptest: true
      store_deps: true
