name: Unit Test (rust)

on:
  workflow_call:
    inputs:
      contract:
        required: true
        type: string

defaults:
  run:
    working-directory: smart-contracts/contracts

jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Get git diff
        uses: technote-space/get-diff-action@v6.1.2
        with:
          PATTERNS: |
            **/**.rs
            **/Cargo.toml
      - name: Install Rust
        if: env.GIT_DIFF
        uses: dtolnay/rust-toolchain@stable
      - name: Run unit-tests
        if: env.GIT_DIFF
        run: cd dex-router-osmosis && cargo unit-test
