// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qoracle/ibc.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/ibc-go/v3/modules/core/02-client/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IBCParams struct {
	AuthorizedChannel string       `protobuf:"bytes,1,opt,name=authorized_channel,json=authorizedChannel,proto3" json:"authorized_channel,omitempty" yaml:"authorized_channel"`
	TimeoutHeight     types.Height `protobuf:"bytes,2,opt,name=timeout_height,json=timeoutHeight,proto3" json:"timeout_height" yaml:"timeout_height"`
	TimeoutTimestamp  uint64       `protobuf:"varint,3,opt,name=timeout_timestamp,json=timeoutTimestamp,proto3" json:"timeout_timestamp,omitempty" yaml:"timeout_timestamp"`
}

func (m *IBCParams) Reset()         { *m = IBCParams{} }
func (m *IBCParams) String() string { return proto.CompactTextString(m) }
func (*IBCParams) ProtoMessage()    {}
func (*IBCParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_c113686d5627716e, []int{0}
}
func (m *IBCParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IBCParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IBCParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IBCParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IBCParams.Merge(m, src)
}
func (m *IBCParams) XXX_Size() int {
	return m.Size()
}
func (m *IBCParams) XXX_DiscardUnknown() {
	xxx_messageInfo_IBCParams.DiscardUnknown(m)
}

var xxx_messageInfo_IBCParams proto.InternalMessageInfo

func (m *IBCParams) GetAuthorizedChannel() string {
	if m != nil {
		return m.AuthorizedChannel
	}
	return ""
}

func (m *IBCParams) GetTimeoutHeight() types.Height {
	if m != nil {
		return m.TimeoutHeight
	}
	return types.Height{}
}

func (m *IBCParams) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*IBCParams)(nil), "abag.quasarnode.qoracle.IBCParams")
}

func init() { proto.RegisterFile("qoracle/ibc.proto", fileDescriptor_c113686d5627716e) }

var fileDescriptor_c113686d5627716e = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcf, 0x4a, 0xc3, 0x30,
	0x1c, 0xc7, 0x9b, 0x29, 0xc2, 0x2a, 0x8a, 0x2b, 0x8a, 0x75, 0xb8, 0x74, 0xf4, 0x34, 0x3c, 0x24,
	0x4c, 0x6f, 0x1e, 0x3b, 0x0f, 0x0e, 0x3c, 0xc8, 0xf0, 0xe4, 0x65, 0xa6, 0x59, 0x68, 0x03, 0x6d,
	0xb3, 0xa5, 0xe9, 0x70, 0x3e, 0x80, 0x67, 0x1f, 0x6b, 0xc7, 0x1d, 0x3d, 0x15, 0x59, 0xdf, 0xa0,
	0x4f, 0x20, 0xfd, 0xe7, 0x18, 0x9e, 0xf2, 0xe3, 0xc3, 0x27, 0xc9, 0x37, 0xdf, 0xe8, 0x9d, 0x85,
	0x90, 0x84, 0x06, 0x0c, 0x73, 0x97, 0xa2, 0xb9, 0x14, 0x4a, 0x18, 0x97, 0xc4, 0x25, 0x1e, 0x5a,
	0x24, 0x24, 0x26, 0x32, 0x12, 0x33, 0x86, 0x6a, 0xa5, 0x7b, 0xee, 0x09, 0x4f, 0x94, 0x0e, 0x2e,
	0xa6, 0x4a, 0xef, 0x5a, 0xdc, 0xa5, 0x98, 0x0a, 0xc9, 0x30, 0x0d, 0x38, 0x8b, 0x14, 0x5e, 0x0e,
	0xeb, 0xa9, 0x12, 0xec, 0xcf, 0x96, 0xde, 0x1e, 0x3b, 0xa3, 0x67, 0x22, 0x49, 0x18, 0x1b, 0x4f,
	0xba, 0x41, 0x12, 0xe5, 0x0b, 0xc9, 0x3f, 0xd8, 0x6c, 0x4a, 0x7d, 0x12, 0x45, 0x2c, 0x30, 0x41,
	0x1f, 0x0c, 0xda, 0x4e, 0x2f, 0x4f, 0xad, 0xab, 0x15, 0x09, 0x83, 0x7b, 0xfb, 0xbf, 0x63, 0x4f,
	0x3a, 0x3b, 0x38, 0xaa, 0x98, 0xf1, 0xa6, 0x9f, 0x2a, 0x1e, 0x32, 0x91, 0xa8, 0xa9, 0xcf, 0xb8,
	0xe7, 0x2b, 0xb3, 0xd5, 0x07, 0x83, 0xe3, 0xdb, 0x2e, 0x2a, 0xde, 0x53, 0xa4, 0x42, 0x75, 0x96,
	0xe5, 0x10, 0x3d, 0x96, 0x86, 0xd3, 0x5b, 0xa7, 0x96, 0x96, 0xa7, 0xd6, 0x45, 0x75, 0xd3, 0xfe,
	0x7e, 0x7b, 0x72, 0x52, 0x83, 0xca, 0x36, 0xc6, 0x7a, 0xa7, 0x31, 0x8a, 0x35, 0x56, 0x24, 0x9c,
	0x9b, 0x07, 0x7d, 0x30, 0x38, 0x74, 0xae, 0xf3, 0xd4, 0x32, 0xf7, 0x0f, 0xf9, 0x53, 0xec, 0xc9,
	0x59, 0xcd, 0x5e, 0x1a, 0xe4, 0x3c, 0xac, 0xb7, 0x10, 0x6c, 0xb6, 0x10, 0xfc, 0x6c, 0x21, 0xf8,
	0xca, 0xa0, 0xb6, 0xc9, 0xa0, 0xf6, 0x9d, 0x41, 0xed, 0xf5, 0xc6, 0xe3, 0xca, 0x4f, 0x5c, 0x44,
	0x45, 0x88, 0x8b, 0xf6, 0xf1, 0xae, 0x7d, 0xfc, 0x8e, 0x9b, 0x2f, 0x52, 0xab, 0x39, 0x8b, 0xdd,
	0xa3, 0xb2, 0xd5, 0xbb, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa0, 0xa6, 0xf7, 0x5c, 0xba, 0x01,
	0x00, 0x00,
}

func (m *IBCParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IBCParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IBCParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintIbc(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.TimeoutHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintIbc(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.AuthorizedChannel) > 0 {
		i -= len(m.AuthorizedChannel)
		copy(dAtA[i:], m.AuthorizedChannel)
		i = encodeVarintIbc(dAtA, i, uint64(len(m.AuthorizedChannel)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIbc(dAtA []byte, offset int, v uint64) int {
	offset -= sovIbc(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IBCParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AuthorizedChannel)
	if l > 0 {
		n += 1 + l + sovIbc(uint64(l))
	}
	l = m.TimeoutHeight.Size()
	n += 1 + l + sovIbc(uint64(l))
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovIbc(uint64(m.TimeoutTimestamp))
	}
	return n
}

func sovIbc(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIbc(x uint64) (n int) {
	return sovIbc(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IBCParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IBCParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IBCParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorizedChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorizedChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthIbc
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthIbc
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TimeoutHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipIbc(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIbc
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIbc(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIbc
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIbc
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIbc
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIbc
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIbc
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIbc        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIbc          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIbc = fmt.Errorf("proto: unexpected end of group")
)
