// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: qoracle/pool_info.proto

package types

import (
	fmt "fmt"
	balancer "github.com/abag/quasarnode/osmosis/v9/gamm/pool-models/balancer"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PoolInfo struct {
	PoolId          string         `protobuf:"bytes,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
	Info            *balancer.Pool `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	LastUpdatedTime uint64         `protobuf:"varint,3,opt,name=lastUpdatedTime,proto3" json:"lastUpdatedTime,omitempty"`
	Creator         string         `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
}

func (m *PoolInfo) Reset()         { *m = PoolInfo{} }
func (m *PoolInfo) String() string { return proto.CompactTextString(m) }
func (*PoolInfo) ProtoMessage()    {}
func (*PoolInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_58ae13543ed982a2, []int{0}
}
func (m *PoolInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PoolInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PoolInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PoolInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PoolInfo.Merge(m, src)
}
func (m *PoolInfo) XXX_Size() int {
	return m.Size()
}
func (m *PoolInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PoolInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PoolInfo proto.InternalMessageInfo

func (m *PoolInfo) GetPoolId() string {
	if m != nil {
		return m.PoolId
	}
	return ""
}

func (m *PoolInfo) GetInfo() *balancer.Pool {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *PoolInfo) GetLastUpdatedTime() uint64 {
	if m != nil {
		return m.LastUpdatedTime
	}
	return 0
}

func (m *PoolInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func init() {
	proto.RegisterType((*PoolInfo)(nil), "abag.quasarnode.qoracle.PoolInfo")
}

func init() { proto.RegisterFile("qoracle/pool_info.proto", fileDescriptor_58ae13543ed982a2) }

var fileDescriptor_58ae13543ed982a2 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x50, 0xbf, 0x4a, 0xfc, 0x40,
	0x10, 0xce, 0xfe, 0x7e, 0xe1, 0xd4, 0xb5, 0x10, 0x52, 0x78, 0xe1, 0x8a, 0x25, 0x58, 0x05, 0xc1,
	0x5d, 0x4e, 0x0b, 0xb1, 0x15, 0x9b, 0xeb, 0x24, 0x68, 0x63, 0x23, 0x93, 0x64, 0x2f, 0x06, 0x76,
	0x33, 0xb9, 0xdd, 0xbd, 0x43, 0xdf, 0xc2, 0xca, 0x67, 0xb2, 0xbc, 0xd2, 0x52, 0x92, 0x17, 0x91,
	0x8d, 0x39, 0x05, 0xbb, 0xf9, 0x86, 0xef, 0xcf, 0xcc, 0x47, 0xa7, 0x2b, 0x34, 0x50, 0x28, 0x29,
	0x5a, 0x44, 0xf5, 0x58, 0x37, 0x4b, 0xe4, 0xad, 0x41, 0x87, 0xd1, 0x14, 0x72, 0xa8, 0xf8, 0x6a,
	0x0d, 0x16, 0x4c, 0x83, 0xa5, 0xe4, 0x23, 0x71, 0x76, 0x89, 0x56, 0xa3, 0xad, 0xad, 0xd8, 0x5c,
	0x89, 0x0a, 0xb4, 0x1e, 0x94, 0x67, 0x1a, 0x4b, 0xa9, 0xac, 0xc8, 0x41, 0x41, 0x53, 0x48, 0xf3,
	0x33, 0xdc, 0x22, 0xaa, 0x6f, 0xc7, 0x93, 0x37, 0x42, 0xf7, 0x3d, 0x5c, 0x34, 0x4b, 0x8c, 0x8e,
	0xe9, 0xc4, 0xeb, 0x16, 0x65, 0x4c, 0x12, 0x92, 0x1e, 0x64, 0x23, 0x8a, 0x38, 0x0d, 0xfd, 0x11,
	0xf1, 0xbf, 0x84, 0xa4, 0x87, 0xe7, 0x33, 0x3e, 0x86, 0x71, 0x9f, 0xc4, 0x37, 0xf3, 0x5c, 0x3a,
	0x98, 0x73, 0xef, 0x92, 0x0d, 0xbc, 0x28, 0xa5, 0x47, 0x0a, 0xac, 0xbb, 0x6f, 0x4b, 0x70, 0xb2,
	0xbc, 0xab, 0xb5, 0x8c, 0xff, 0x27, 0x24, 0x0d, 0xb3, 0xbf, 0xeb, 0x28, 0xa6, 0x7b, 0x85, 0x91,
	0xe0, 0xd0, 0xc4, 0xe1, 0x10, 0xb9, 0x83, 0xd7, 0x37, 0xef, 0x1d, 0x23, 0xdb, 0x8e, 0x91, 0xcf,
	0x8e, 0x91, 0xd7, 0x9e, 0x05, 0xdb, 0x9e, 0x05, 0x1f, 0x3d, 0x0b, 0x1e, 0x4e, 0xab, 0xda, 0x3d,
	0xad, 0x73, 0x5e, 0xa0, 0x16, 0xbe, 0x0f, 0xf1, 0xdb, 0x87, 0x78, 0x16, 0xbb, 0xea, 0xdc, 0x4b,
	0x2b, 0x6d, 0x3e, 0x19, 0xbe, 0xbc, 0xf8, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x99, 0x43, 0x9c, 0x3b,
	0x52, 0x01, 0x00, 0x00,
}

func (m *PoolInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PoolInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PoolInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintPoolInfo(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0x22
	}
	if m.LastUpdatedTime != 0 {
		i = encodeVarintPoolInfo(dAtA, i, uint64(m.LastUpdatedTime))
		i--
		dAtA[i] = 0x18
	}
	if m.Info != nil {
		{
			size, err := m.Info.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPoolInfo(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.PoolId) > 0 {
		i -= len(m.PoolId)
		copy(dAtA[i:], m.PoolId)
		i = encodeVarintPoolInfo(dAtA, i, uint64(len(m.PoolId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPoolInfo(dAtA []byte, offset int, v uint64) int {
	offset -= sovPoolInfo(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PoolInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolId)
	if l > 0 {
		n += 1 + l + sovPoolInfo(uint64(l))
	}
	if m.Info != nil {
		l = m.Info.Size()
		n += 1 + l + sovPoolInfo(uint64(l))
	}
	if m.LastUpdatedTime != 0 {
		n += 1 + sovPoolInfo(uint64(m.LastUpdatedTime))
	}
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovPoolInfo(uint64(l))
	}
	return n
}

func sovPoolInfo(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPoolInfo(x uint64) (n int) {
	return sovPoolInfo(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PoolInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPoolInfo
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PoolInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PoolInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Info", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPoolInfo
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPoolInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Info == nil {
				m.Info = &balancer.Pool{}
			}
			if err := m.Info.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdatedTime", wireType)
			}
			m.LastUpdatedTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LastUpdatedTime |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPoolInfo
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPoolInfo
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPoolInfo(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPoolInfo
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPoolInfo(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPoolInfo
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPoolInfo
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPoolInfo
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPoolInfo
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPoolInfo
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPoolInfo        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPoolInfo          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPoolInfo = fmt.Errorf("proto: unexpected end of group")
)
